package formularios;

import Classes.Cliente;
import Classes.Usuarios;
import ClassesDAO.UsuarioDAO;
import ClassesDao.ClienteDAO;
import Formatadores.CNPJ;
import Formatadores.CPF;
import GeradorID.gerarId;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static formularios.frmMenuPrincipal.JDesktopPanePrincipall;
/**
 *
 * @author João Carlos Batista
 */
public class FrmCliente_OLD extends javax.swing.JInternalFrame {

    private String documento;
    private String docAuxi;
    private Object mensagem;
    private int idCliente;
    /**
     * Creates new form frmCliente
     */
    public FrmCliente_OLD(int idCliente) {
        initComponents();
        tratarTipoPessoa();
        
        cmbTpPes.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent ie) {

                tratarTipoPessoa();
                
            }
        });
    }

    FrmCliente_OLD() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTipPes = new javax.swing.JLabel();
        cmbTpPes = new javax.swing.JComboBox<>();
        lblEndereco = new javax.swing.JLabel();
        lblCpf_Cnpj = new javax.swing.JLabel();
        txtCpf_Cnpj = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblTelResidencial = new javax.swing.JLabel();
        jtxtTelResidencial = new javax.swing.JFormattedTextField();
        lblTelCelular = new javax.swing.JLabel();
        jtxtTelCelular = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Cadastro de Cliente");
        setPreferredSize(new java.awt.Dimension(580, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome");
        lblNome.setName("lblNome"); // NOI18N
        pnlPrincipal.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtNome.setName("txtNome"); // NOI18N
        pnlPrincipal.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 360, -1));

        lblTipPes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTipPes.setText("Tipo de pessoa");
        lblTipPes.setName("lblTipPes"); // NOI18N
        pnlPrincipal.add(lblTipPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        cmbTpPes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTpPes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Pessoa", "Física", "Jurídica" }));
        cmbTpPes.setName("cmbTpPes"); // NOI18N
        cmbTpPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTpPesActionPerformed(evt);
            }
        });
        pnlPrincipal.add(cmbTpPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 140, -1));

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço");
        lblEndereco.setName("lblEndereco"); // NOI18N
        pnlPrincipal.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lblCpf_Cnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCpf_Cnpj.setText("CPF/CNPJ");
        lblCpf_Cnpj.setName("lblCpf_Cnpj"); // NOI18N
        pnlPrincipal.add(lblCpf_Cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtCpf_Cnpj.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtCpf_Cnpj.setName("txtCpf_Cnpj"); // NOI18N
        txtCpf_Cnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpf_CnpjFocusLost(evt);
            }
        });
        txtCpf_Cnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpf_CnpjKeyPressed(evt);
            }
        });
        pnlPrincipal.add(txtCpf_Cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, -1));

        txtEndereco.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtEndereco.setName("txtEndereco"); // NOI18N
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 310, -1));

        lblBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBairro.setText("Bairro");
        lblBairro.setName("lblBairro"); // NOI18N
        pnlPrincipal.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        txtBairro.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtBairro.setName("txtBairro"); // NOI18N
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 190, -1));

        lblTelResidencial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelResidencial.setText("Tel. Residencial");
        lblTelResidencial.setName("lblTelResidencial"); // NOI18N
        pnlPrincipal.add(lblTelResidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        try {
            jtxtTelResidencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtTelResidencial.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jtxtTelResidencial.setName("jtxtTelResidencial"); // NOI18N
        jtxtTelResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelResidencialActionPerformed(evt);
            }
        });
        pnlPrincipal.add(jtxtTelResidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, -1));

        lblTelCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelCelular.setText("Tel. Celular");
        lblTelCelular.setName("lblTelCelular"); // NOI18N
        pnlPrincipal.add(lblTelCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        try {
            jtxtTelCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtTelCelular.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jtxtTelCelular.setName("jtxtTelCelular"); // NOI18N
        jtxtTelCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelCelularActionPerformed(evt);
            }
        });
        pnlPrincipal.add(jtxtTelCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setName("lblEmail"); // NOI18N
        pnlPrincipal.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        txtEmail.setName("txtEmail"); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 240, -1));

        btnFechar.setBackground(new java.awt.Color(249, 105, 14));
        btnFechar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("Fechar");
        btnFechar.setBorderPainted(false);
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.setName("btnFechar"); // NOI18N
        btnFechar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFecharMouseExited(evt);
            }
        });
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(1, 50, 67));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTpPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTpPesActionPerformed

    }//GEN-LAST:event_cmbTpPesActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void btnFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseEntered
        btnFechar.setBackground(new Color(249, 105, 40));
        btnFechar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnFecharMouseEntered

    private void btnFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseExited
        btnFechar.setBackground(new Color(249, 105, 14));
        btnFechar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnFecharMouseExited

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered

        btnSalvar.setBackground(new Color(1, 50, 90));
        btnSalvar.setForeground(Color.WHITE);
        //passa o mouse em cima
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited

        btnSalvar.setBackground(new Color(1, 50, 67));
        btnSalvar.setForeground(Color.WHITE);
        //hora que o mouse sai de cima
    }//GEN-LAST:event_btnSalvarMouseExited

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (camposObrigatorios()) {
            JOptionPane.showMessageDialog(this, mensagem, "Alerta", 0,
                    new ImageIcon(getClass().getResource("/imagens/icons/info_P.png")));
        } else {
            Cliente cliente = new Cliente();
            cliente.setCli_Nom(txtNome.getText());
            cliente.setCli_Tip_Pes(cmbTpPes.getSelectedItem().toString());
            cliente.setCli_Cpf_Cnpj(txtCpf_Cnpj.getText());
            cliente.setCli_End(txtEndereco.getText());
            cliente.setCli_Bai(txtBairro.getText());
            cliente.setCli_Tel_Res(jtxtTelResidencial.getText());
            cliente.setCli_Tel_Cel(jtxtTelCelular.getText());
            cliente.setCli_Ema(txtEmail.getText());

            if (idCliente == 0) {
                cliente.setCli_Cod(gerarId.gerarIdCliente());
                idCliente = cliente.getCli_Cod();
                ClienteDAO.gravarCliente(cliente);
            } else {
                cliente.setCli_Cod(idCliente);
                ClienteDAO.alterarCliente(cliente);
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCpf_CnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpf_CnpjKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpf_CnpjKeyPressed

    private void txtCpf_CnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpf_CnpjFocusLost

        documento = txtCpf_Cnpj.getText();

        if (!documento.isEmpty()) {
            if (docAuxi != documento) {
                if (cmbTpPes.getSelectedIndex() == 1) {
                    CPF pf = new CPF(documento);
                    if (pf.isCPF()) {
                        txtCpf_Cnpj.setText(pf.getCPF(true));
                        docAuxi = txtCpf_Cnpj.getText();
                        
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "CPF inválido!");
                    }
                } else {
                    if (cmbTpPes.getSelectedIndex() == 2) {
                        CNPJ pj = new CNPJ(documento);
                        if (pj.isCNPJ()) {
                            txtCpf_Cnpj.setText(pj.getCNPJ(true));
                            docAuxi = txtCpf_Cnpj.getText();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "CNPJ inválido!");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_txtCpf_CnpjFocusLost

    private void jtxtTelResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelResidencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelResidencialActionPerformed

    private void jtxtTelCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelCelularActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void tratarTipoPessoa() {

        txtCpf_Cnpj.setText("");
        if (cmbTpPes.getSelectedIndex() == 0) {
            lblCpf_Cnpj.setText("CPF/CNPJ");
            txtCpf_Cnpj.enable(false);

        } else {
            if (cmbTpPes.getSelectedIndex() == 1) {
                lblCpf_Cnpj.setText("CPF");
                txtCpf_Cnpj.enable(true);
            } else {
                lblCpf_Cnpj.setText("CNPJ");
                txtCpf_Cnpj.enable(true);
            }
        }
    }
    
    private boolean camposObrigatorios() {

        boolean retorno = false;
        mensagem = "Preenchimento obrigatório\n do(s) campo(s) abaixo:\n\n";

        if (txtNome.getText().equals("")) {
            mensagem += "Nome;";
            retorno = true;
        }

        return retorno;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTpPes;
    private javax.swing.JFormattedTextField jtxtTelCelular;
    private javax.swing.JFormattedTextField jtxtTelResidencial;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCpf_Cnpj;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelCelular;
    private javax.swing.JLabel lblTelResidencial;
    private javax.swing.JLabel lblTipPes;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCpf_Cnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

}
