/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Classes.OrdemServico;
import Classes.StatusRegistro;
import Classes.Veiculo;
import ClassesDao.OrdemServicoDAO;
import ClassesEnum.StatusOS;
import GeradorID.gerarId;
import static formularios.frmMenuPrincipal.JDesktopPanePrincipall;
import java.awt.Color;
import java.awt.Dimension;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author João Carlos Batista
 */
public class FrmGerarOrcamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmOrdemServico
     */
    String origem;
    int vei_Cod = 0;
    boolean error;

    public FrmGerarOrcamento(Veiculo veiculo, String origem) {
        initComponents();
        this.origem = origem;
        txtProprietario.setText(veiculo.getCli_Nom());
        txtPlaca.setText(veiculo.getVei_Placa());
        txtModelo.setText(veiculo.getVei_Mod());
        txtFabricante.setText(veiculo.getVei_Fab());
        txtAnoFab.setText(String.valueOf(veiculo.getVei_Ano_Fab()));
        txtCor.setText(veiculo.getVei_Cor());
        txtCombustivel.setText(veiculo.getVei_Com());
        this.vei_Cod = veiculo.getVei_Cod();

        if (origem == "O") {
            btnGerarOS.setText("Gerar orçamento");
        } else {
            btnGerarOS.setText("Gerar serviço");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlprincipal = new javax.swing.JPanel();
        pnlVeiculo = new javax.swing.JPanel();
        lblProprietario = new javax.swing.JLabel();
        txtProprietario = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblFabricante = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        lblAnoFab = new javax.swing.JLabel();
        txtAnoFab = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblCombustivel = new javax.swing.JLabel();
        txtCombustivel = new javax.swing.JTextField();
        btnRetornar = new javax.swing.JButton();
        btnGerarOS = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Gerar Orçamento");
        setPreferredSize(new java.awt.Dimension(765, 260));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlprincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlprincipal.setName("pnlprincipal"); // NOI18N
        pnlprincipal.setPreferredSize(new java.awt.Dimension(870, 540));
        pnlprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        pnlVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        pnlVeiculo.setMinimumSize(new java.awt.Dimension(720, 141));
        pnlVeiculo.setName("pnlVeiculo"); // NOI18N
        pnlVeiculo.setPreferredSize(new java.awt.Dimension(770, 170));
        pnlVeiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProprietario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProprietario.setText("Proprietário");
        lblProprietario.setName("lblProprietario"); // NOI18N
        pnlVeiculo.add(lblProprietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 40, -1, -1));

        txtProprietario.setEditable(false);
        txtProprietario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtProprietario.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtProprietario.setEnabled(false);
        txtProprietario.setName("txtProprietario"); // NOI18N
        txtProprietario.setPreferredSize(new java.awt.Dimension(400, 25));
        pnlVeiculo.add(txtProprietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, 400, -1));

        lblPlaca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPlaca.setText("Placa");
        lblPlaca.setName("lblPlaca"); // NOI18N
        pnlVeiculo.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 40, -1, -1));

        txtPlaca.setEditable(false);
        txtPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPlaca.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtPlaca.setEnabled(false);
        txtPlaca.setName("txtPlaca"); // NOI18N
        txtPlaca.setPreferredSize(new java.awt.Dimension(85, 25));
        pnlVeiculo.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 60, 85, -1));

        lblModelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblModelo.setText("Modelo");
        lblModelo.setName("lblModelo"); // NOI18N
        pnlVeiculo.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 100, -1, -1));

        txtModelo.setEditable(false);
        txtModelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtModelo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtModelo.setEnabled(false);
        txtModelo.setName("txtModelo"); // NOI18N
        txtModelo.setPreferredSize(new java.awt.Dimension(310, 25));
        pnlVeiculo.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, 310, -1));

        lblFabricante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFabricante.setText("Fabricante");
        lblFabricante.setName("lblFabricante"); // NOI18N
        pnlVeiculo.add(lblFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        txtFabricante.setEditable(false);
        txtFabricante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFabricante.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtFabricante.setEnabled(false);
        txtFabricante.setName("txtFabricante"); // NOI18N
        txtFabricante.setPreferredSize(new java.awt.Dimension(160, 25));
        txtFabricante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFabricanteFocusLost(evt);
            }
        });
        txtFabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFabricanteKeyPressed(evt);
            }
        });
        pnlVeiculo.add(txtFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 160, -1));

        lblAnoFab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnoFab.setText("Ano Fab.");
        lblAnoFab.setName("lblAnoFab"); // NOI18N
        pnlVeiculo.add(lblAnoFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 100, -1, -1));

        txtAnoFab.setEditable(false);
        txtAnoFab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAnoFab.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtAnoFab.setEnabled(false);
        txtAnoFab.setName("txtAnoFab"); // NOI18N
        txtAnoFab.setPreferredSize(new java.awt.Dimension(70, 25));
        txtAnoFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoFabActionPerformed(evt);
            }
        });
        pnlVeiculo.add(txtAnoFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 120, 70, -1));

        lblCor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCor.setText("Cor");
        lblCor.setName("lblCor"); // NOI18N
        pnlVeiculo.add(lblCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 100, -1, -1));

        txtCor.setEditable(false);
        txtCor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCor.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtCor.setEnabled(false);
        txtCor.setName("txtCor"); // NOI18N
        txtCor.setPreferredSize(new java.awt.Dimension(120, 25));
        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });
        pnlVeiculo.add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 120, 120, -1));

        lblCombustivel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCombustivel.setText("Combustível");
        lblCombustivel.setName("lblCombustivel"); // NOI18N
        pnlVeiculo.add(lblCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 100, -1, -1));

        txtCombustivel.setEditable(false);
        txtCombustivel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCombustivel.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtCombustivel.setEnabled(false);
        txtCombustivel.setName("txtCombustivel"); // NOI18N
        txtCombustivel.setPreferredSize(new java.awt.Dimension(125, 25));
        txtCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCombustivelActionPerformed(evt);
            }
        });
        pnlVeiculo.add(txtCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 120, 125, -1));

        pnlprincipal.add(pnlVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 720, 170));

        btnRetornar.setBackground(new java.awt.Color(249, 105, 14));
        btnRetornar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRetornar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetornar.setText("Retornar");
        btnRetornar.setBorderPainted(false);
        btnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetornar.setName("btnRetornar"); // NOI18N
        btnRetornar.setPreferredSize(new java.awt.Dimension(142, 35));
        btnRetornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRetornarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRetornarMouseExited(evt);
            }
        });
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        pnlprincipal.add(btnRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 188, 142, 35));

        btnGerarOS.setBackground(new java.awt.Color(40, 167, 69));
        btnGerarOS.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGerarOS.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarOS.setText("Gerar Orçamento");
        btnGerarOS.setBorderPainted(false);
        btnGerarOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerarOS.setName("btnGerarOS"); // NOI18N
        btnGerarOS.setPreferredSize(new java.awt.Dimension(142, 35));
        btnGerarOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGerarOSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGerarOSMouseExited(evt);
            }
        });
        btnGerarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarOSActionPerformed(evt);
            }
        });
        pnlprincipal.add(btnGerarOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 188, 142, 35));

        getContentPane().add(pnlprincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFabricanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFabricanteFocusLost

    }//GEN-LAST:event_txtFabricanteFocusLost

    private void txtFabricanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFabricanteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFabricanteKeyPressed

    private void txtAnoFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoFabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoFabActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed

        FrmLocalizarPlacaOrcamento gerarOrcamento = new FrmLocalizarPlacaOrcamento("O");

        JDesktopPanePrincipall.add(gerarOrcamento);
        //Listacliente.setLocation(350,3);
        gerarOrcamento.setVisible(true);
        gerarOrcamento.setPosicao();
        dispose();
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void btnGerarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarOSActionPerformed

        Date dataOrcamento = new Date();
        Date dataEntrada = null;

        if (origem == "S") {
            dataEntrada = new Date();
        }

        OrdemServico ordemServico = new OrdemServico();
        ordemServico.setOs_Cod(gerarId.gerarIdOS());
        ordemServico.setOs_Dat_Orc(dataOrcamento);
        ordemServico.setOs_Dat_Ent(dataEntrada);
        if (origem == "O") {
            ordemServico.setOs_Sit(StatusOS.OR.toString());
        } else {
            ordemServico.setOs_Sit(StatusOS.SEF.toString());
        }
        ordemServico.setVei_Cod(this.vei_Cod);
        
        error = OrdemServicoDAO.gravarOrdemServico(ordemServico);

        if (!error) {
            if (origem == "O") {
                FrmOrcamento frmOrcamento = new FrmOrcamento(ordemServico.getOs_Cod());

                JDesktopPanePrincipall.add(frmOrcamento);
                frmOrcamento.setVisible(true);
                frmOrcamento.setPosicao();
            } else {
                FrmOrdemServico frmOrdemServico = new FrmOrdemServico(ordemServico.getOs_Cod());

                JDesktopPanePrincipall.add(frmOrdemServico);
                frmOrdemServico.setVisible(true);
                frmOrdemServico.setPosicao();
            }

            dispose();
        }
    }//GEN-LAST:event_btnGerarOSActionPerformed

    private void txtCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCombustivelActionPerformed

    private void btnRetornarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetornarMouseEntered
        btnRetornar.setBackground(new Color(249,105,40));
        btnRetornar.setForeground(Color.WHITE);
        btnRetornar.setFont(new java.awt.Font("Arial", 1, 13));
    }//GEN-LAST:event_btnRetornarMouseEntered

    private void btnRetornarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetornarMouseExited
        btnRetornar.setBackground(new Color(249,105,14));
        btnRetornar.setForeground(Color.WHITE);
        btnRetornar.setFont(new java.awt.Font("Arial", 1, 12));
    }//GEN-LAST:event_btnRetornarMouseExited

    private void btnGerarOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarOSMouseEntered
        btnGerarOS.setBackground(new Color(33,126,56));
        btnGerarOS.setForeground(new Color(255,255,255));
        btnGerarOS.setFont(new java.awt.Font("Arial", 1, 13));
    }//GEN-LAST:event_btnGerarOSMouseEntered

    private void btnGerarOSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarOSMouseExited
        btnGerarOS.setBackground(new Color(40,167,69));
        btnGerarOS.setForeground(new Color(255,255,255));
        btnGerarOS.setFont(new java.awt.Font("Arial", 1, 12));
    }//GEN-LAST:event_btnGerarOSMouseExited

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarOS;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JLabel lblAnoFab;
    private javax.swing.JLabel lblCombustivel;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblProprietario;
    private javax.swing.JPanel pnlVeiculo;
    private javax.swing.JPanel pnlprincipal;
    private javax.swing.JTextField txtAnoFab;
    private javax.swing.JTextField txtCombustivel;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtProprietario;
    // End of variables declaration//GEN-END:variables

}
