package formularios;

import Classes.ItemOS;
import ClassesDao.OrdemServicoItemDAO;
import Formatadores.LetrasMaiusculas;
import GeradorID.gerarId;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
/**
 *
 * @author João Carlos Batista
 */
public class FrmInserirPecaOS extends javax.swing.JInternalFrame {

    FrmUsuario usuariocad;
    String codigoProduto = "";
    double valorUnit;
    int os_Cod = 0;
    boolean selecionado = false;
    String origem = "";

    public FrmInserirPecaOS(int os_Cod, String origem) {
        initComponents();
        this.os_Cod = os_Cod;
        this.origem = origem;
        txtDescricao.setDocument(new LetrasMaiusculas());
        txtPeca.setDocument(new LetrasMaiusculas());
        tblPeca.getColumnModel().getColumn(0).setMinWidth(0);
        tblPeca.getColumnModel().getColumn(0).setMaxWidth(0);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtPeca = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPanePeca = new javax.swing.JScrollPane();
        tblPeca = new javax.swing.JTable();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblQuant = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(658, 490));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(900, 500));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        pnlCabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Consulta de Peças", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        pnlCabecalho.setPreferredSize(new java.awt.Dimension(610, 90));
        pnlCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setText("Descrição");
        lblNome.setName("lblNome"); // NOI18N
        pnlCabecalho.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        txtPeca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPeca.setForeground(new java.awt.Color(51, 51, 51));
        txtPeca.setName("txtPeca"); // NOI18N
        txtPeca.setPreferredSize(new java.awt.Dimension(290, 25));
        pnlCabecalho.add(txtPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 290, -1));

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_P.png"))); // NOI18N
        btnPesquisar.setToolTipText("");
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_M.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 41, -1, -1));

        pnlPrincipal.add(pnlCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 610, 90));

        jScrollPanePeca.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPanePeca.setAutoscrolls(true);
        jScrollPanePeca.setName("jScrollPanePeca"); // NOI18N
        jScrollPanePeca.setPreferredSize(new java.awt.Dimension(610, 240));

        tblPeca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblPeca.setForeground(new java.awt.Color(51, 51, 51));
        tblPeca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Valor Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPeca.setGridColor(new java.awt.Color(255, 255, 255));
        tblPeca.setName("tblPeca"); // NOI18N
        tblPeca.setPreferredSize(new java.awt.Dimension(600, 140));
        tblPeca.setRowHeight(20);
        tblPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPecaMouseClicked(evt);
            }
        });
        jScrollPanePeca.setViewportView(tblPeca);
        if (tblPeca.getColumnModel().getColumnCount() > 0) {
            tblPeca.getColumnModel().getColumn(0).setResizable(false);
            tblPeca.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblPeca.getColumnModel().getColumn(1).setResizable(false);
            tblPeca.getColumnModel().getColumn(1).setPreferredWidth(400);
            tblPeca.getColumnModel().getColumn(2).setResizable(false);
            tblPeca.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblPeca.getColumnModel().getColumn(3).setResizable(false);
            tblPeca.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        pnlPrincipal.add(jScrollPanePeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 610, -1));

        lblDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição");
        lblDescricao.setName("lblDescricao"); // NOI18N
        pnlPrincipal.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, -1, -1));

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(51, 51, 51));
        txtDescricao.setName("txtPlaca"); // NOI18N
        txtDescricao.setPreferredSize(new java.awt.Dimension(360, 25));
        pnlPrincipal.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, 360, -1));

        lblQuant.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblQuant.setText("Quantidade");
        lblQuant.setName("lblQuant"); // NOI18N
        pnlPrincipal.add(lblQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 120, -1, -1));

        txtQuant.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtQuant.setForeground(new java.awt.Color(51, 51, 51));
        txtQuant.setName("txtQuant"); // NOI18N
        txtQuant.setPreferredSize(new java.awt.Dimension(70, 25));
        pnlPrincipal.add(txtQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 140, 70, -1));

        btnInserir.setBackground(new java.awt.Color(0, 123, 255));
        btnInserir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnInserir.setForeground(new java.awt.Color(255, 255, 255));
        btnInserir.setText("Inserir");
        btnInserir.setBorderPainted(false);
        btnInserir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInserir.setName("btnInserir"); // NOI18N
        btnInserir.setPreferredSize(new java.awt.Dimension(90, 40));
        btnInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInserirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInserirMouseExited(evt);
            }
        });
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 130, -1, -1));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if (txtPeca.equals("")) {
            OrdemServicoItemDAO.listarPeca("");
        } else {
            OrdemServicoItemDAO.listarPeca(txtPeca.getText().trim());
        }
        dimensionarTabela();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if (selecionado) {
            ItemOS itemos = new ItemOS();
            itemos.setOs_Cod(os_Cod);
            itemos.setOs_Item_Cod(gerarId.gerarIdOrdemServicoItem(os_Cod));
            itemos.setOs_Item_Prod_Cod(Integer.parseInt(codigoProduto));
            itemos.setOs_Item_Qua(Integer.parseInt(txtQuant.getText()));
            itemos.setOs_Item_Val(valorUnit);

            OrdemServicoItemDAO.gravarOrdemServicoItem(itemos);
            
            if(origem == "O"){
                OrdemServicoItemDAO.listarOrdemServicoItem(os_Cod, "O");                
            }
            else{
                OrdemServicoItemDAO.listarOrdemServicoItem(os_Cod, "S");
                FrmOrdemServico.dimensionarTabelaPeca();
            }            
            txtDescricao.setText("");
            txtQuant.setText("");
            selecionado = false;
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item com duplo click do mouse.");
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnInserirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirMouseEntered
        btnInserir.setBackground(new Color(0, 80, 217));
        btnInserir.setForeground(new Color(255, 255, 255));
        btnInserir.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnInserirMouseEntered

    private void btnInserirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirMouseExited
        btnInserir.setBackground(new Color(0, 123, 255));
        btnInserir.setForeground(new Color(255, 255, 255));
        btnInserir.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnInserirMouseExited

    private void tblPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPecaMouseClicked
        if (evt.getClickCount() == 2) {
            selecionado = true;
            valorUnit = 0;
            int linha = tblPeca.getSelectedRow();
            codigoProduto = tblPeca.getValueAt(linha, 0).toString();
            txtDescricao.setText(tblPeca.getValueAt(linha, 1).toString());
            txtQuant.setText("1");
            valorUnit = Double.parseDouble(tblPeca.getValueAt(linha, 3).toString());
        }
    }//GEN-LAST:event_tblPecaMouseClicked

    private void preencherTabela() {
        if (tblPeca.getSelectedRow() > -1) {
            tblPeca.removeRowSelectionInterval(tblPeca.getSelectedRow(), tblPeca.getSelectedRow());
        }
        txtPeca.setText("");
        OrdemServicoItemDAO.listarPeca("");
        dimensionarTabela();    
    }
   
    private void dimensionarTabela(){
        int altura = 20 * tblPeca.getRowCount();
        tblPeca.setPreferredSize(new java.awt.Dimension(610, altura));    
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPanePeca;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlPrincipal;
    public static javax.swing.JTable tblPeca;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPeca;
    private javax.swing.JTextField txtQuant;
    // End of variables declaration//GEN-END:variables
}
