package formularios;

import Classes.Veiculo;
import ClassesDao.OrdemServicoDAO;
import Formatadores.LetrasMaiusculas;
import static formularios.frmMenuPrincipal.JDesktopPanePrincipall;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author João Carlos Batista
 */
public class FrmLocalizarPlacaOrcamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListaUsuario
     */
    FrmUsuario usuariocad;
    String origem;
    public FrmLocalizarPlacaOrcamento(String origem) {
        initComponents();
        
        this.origem = origem;
        
        jtxtPlaca.setDocument(new LetrasMaiusculas());

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        jtxtPlaca = new javax.swing.JFormattedTextField();
        btnPesquisarVeiculo = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(312, 200));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(900, 500));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        pnlCabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Localizar Veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        pnlCabecalho.setMinimumSize(new java.awt.Dimension(273, 111));
        pnlCabecalho.setName("pnlCabecalho"); // NOI18N
        pnlCabecalho.setPreferredSize(new java.awt.Dimension(320, 110));
        pnlCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setText("Placa do veículo");
        lblNome.setName("lblNome"); // NOI18N
        pnlCabecalho.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        btnNovo.setBackground(new java.awt.Color(40, 167, 69));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Avançar");
        btnNovo.setBorderPainted(false);
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.setPreferredSize(new java.awt.Dimension(90, 35));
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoMouseExited(evt);
            }
        });
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 95, 110, -1));

        jtxtPlaca.setForeground(new java.awt.Color(51, 51, 51));
        try {
            jtxtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtPlaca.setToolTipText("");
        jtxtPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtPlaca.setName("jtxtPlaca"); // NOI18N
        jtxtPlaca.setPreferredSize(new java.awt.Dimension(140, 25));
        pnlCabecalho.add(jtxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, 30));

        btnPesquisarVeiculo.setBackground(new java.awt.Color(0, 123, 255));
        btnPesquisarVeiculo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarVeiculo.setText("Pesquisar");
        btnPesquisarVeiculo.setBorderPainted(false);
        btnPesquisarVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarVeiculo.setName("btnPesquisarVeiculo"); // NOI18N
        btnPesquisarVeiculo.setPreferredSize(new java.awt.Dimension(90, 35));
        btnPesquisarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarVeiculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarVeiculoMouseExited(evt);
            }
        });
        btnPesquisarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarVeiculoActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnPesquisarVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, 110, -1));

        pnlPrincipal.add(pnlCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 273, 150));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        String placa = jtxtPlaca.getText().trim();
        placa = placa.replace("-","");
        
        if (placa.length() > 0) {
            Veiculo veiculo = OrdemServicoDAO.PesquisarVeiculoVeiculo(jtxtPlaca.getText().trim(), 0);

            if (veiculo.getVei_Cod() > 0) {
                FrmGerarOrcamento gerarOrcamento = new FrmGerarOrcamento(veiculo, origem);

                JDesktopPanePrincipall.add(gerarOrcamento);
                gerarOrcamento.setVisible(true);
                gerarOrcamento.setPosicao();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Veículo não encontrado.\n Verifique se a placa está correta "
                        + "e tente novamente.\nCaso não tenha encontrado clique o botão 'Pesquisar Veículo'.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Veículo não encontrado.\n Verifique se a placa está correta "
                    + "e tente novamente.\nCaso não tenha encontrado clique o botão 'Pesquisar Veículo'.");
        }
        //Calendar data = Calendar.getInstance();

        //SimpleDateFormat dataFormatada = new SimpleDateFormat("dd-MM-yyyy");
        //JOptionPane.showMessageDialog(null, "Hoje é: " + dataFormatada.format(data.getTime()));
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseEntered
        btnNovo.setBackground(new Color(33, 126, 56));
        btnNovo.setForeground(new Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnNovoMouseEntered

    private void btnNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseExited
        btnNovo.setBackground(new Color(40, 167, 69));
        btnNovo.setForeground(new Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnNovoMouseExited

    private void btnPesquisarVeiculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarVeiculoMouseEntered
        btnPesquisarVeiculo.setBackground(new Color(0, 80, 217));
        btnPesquisarVeiculo.setForeground(new Color(255, 255, 255));
        btnPesquisarVeiculo.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnPesquisarVeiculoMouseEntered

    private void btnPesquisarVeiculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarVeiculoMouseExited
        btnPesquisarVeiculo.setBackground(new Color(0, 123, 255));
        btnPesquisarVeiculo.setForeground(new Color(255, 255, 255));
        btnPesquisarVeiculo.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnPesquisarVeiculoMouseExited

    private void btnPesquisarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarVeiculoActionPerformed
        
        FrmListarVeiculo listarVeiculo = new FrmListarVeiculo(origem);   
        JDesktopPanePrincipall.add(listarVeiculo);
        listarVeiculo.setVisible(true);
        listarVeiculo.setPosicao();           
    }//GEN-LAST:event_btnPesquisarVeiculoActionPerformed
   
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisarVeiculo;
    private javax.swing.JFormattedTextField jtxtPlaca;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
