package formularios;

import Classes.Veiculo;
import ClassesDao.ClienteDAO;
import ClassesDao.OrdemServicoDAO;
import ClassesDao.VeiculoDAO;
import Formatadores.LetrasMaiusculas;
import static formularios.frmMenuPrincipal.JDesktopPanePrincipall;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
/**
 *
 * @author João Carlos Batista
 */
public class FrmListarVeiculo extends javax.swing.JInternalFrame {

    FrmUsuario usuariocad;
    String origem;
    public FrmListarVeiculo(String origem) {
        initComponents();       
        this.origem = origem;
        txtProprietario.setDocument(new LetrasMaiusculas());
        tblVeiculo.getColumnModel().getColumn(0).setMinWidth(0);
        tblVeiculo.getColumnModel().getColumn(0).setMaxWidth(0);
        preencherTabela();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtProprietario = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        jtxtPlaca = new javax.swing.JFormattedTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPaneVeiculo = new javax.swing.JScrollPane();
        tblVeiculo = new javax.swing.JTable();
        btnGerarOS = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(940, 500));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(900, 500));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        pnlCabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Consulta de proprietário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        pnlCabecalho.setPreferredSize(new java.awt.Dimension(890, 110));
        pnlCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setText("Proprietário");
        lblNome.setName("lblNome"); // NOI18N
        pnlCabecalho.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtProprietario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtProprietario.setName("txtProprietario"); // NOI18N
        txtProprietario.setPreferredSize(new java.awt.Dimension(290, 25));
        pnlCabecalho.add(txtProprietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, -1));

        lblPlaca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPlaca.setText("Placa do veículo");
        lblPlaca.setName("lblNome"); // NOI18N
        pnlCabecalho.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jtxtPlaca.setForeground(new java.awt.Color(51, 51, 51));
        try {
            jtxtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtPlaca.setToolTipText("");
        jtxtPlaca.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jtxtPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtPlaca.setName("jtxtPlaca"); // NOI18N
        jtxtPlaca.setPreferredSize(new java.awt.Dimension(140, 25));
        pnlCabecalho.add(jtxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 140, 30));

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_P.png"))); // NOI18N
        btnPesquisar.setToolTipText("");
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_M.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        pnlPrincipal.add(pnlCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 890, -1));

        jScrollPaneVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneVeiculo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneVeiculo.setAutoscrolls(true);
        jScrollPaneVeiculo.setName("jScrollPaneVeiculo"); // NOI18N
        jScrollPaneVeiculo.setPreferredSize(new java.awt.Dimension(860, 240));

        tblVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblVeiculo.setForeground(new java.awt.Color(51, 51, 51));
        tblVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Proprietário", "Placa", "Fabricante", "Modelo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVeiculo.setGridColor(new java.awt.Color(255, 255, 255));
        tblVeiculo.setName("tblVeiculo"); // NOI18N
        tblVeiculo.setPreferredSize(new java.awt.Dimension(870, 140));
        tblVeiculo.setRowHeight(20);
        tblVeiculo.setRowMargin(5);
        jScrollPaneVeiculo.setViewportView(tblVeiculo);
        if (tblVeiculo.getColumnModel().getColumnCount() > 0) {
            tblVeiculo.getColumnModel().getColumn(0).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblVeiculo.getColumnModel().getColumn(1).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(1).setPreferredWidth(340);
            tblVeiculo.getColumnModel().getColumn(2).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblVeiculo.getColumnModel().getColumn(3).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblVeiculo.getColumnModel().getColumn(4).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(4).setPreferredWidth(300);
        }

        pnlPrincipal.add(jScrollPaneVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 145, 890, -1));

        btnGerarOS.setBackground(new java.awt.Color(40, 167, 69));
        btnGerarOS.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnGerarOS.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarOS.setText("Avançar");
        btnGerarOS.setBorderPainted(false);
        btnGerarOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerarOS.setName("btnGerarOS"); // NOI18N
        btnGerarOS.setPreferredSize(new java.awt.Dimension(100, 40));
        btnGerarOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGerarOSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGerarOSMouseExited(evt);
            }
        });
        btnGerarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarOSActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnGerarOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 405, 100, -1));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        String placa = jtxtPlaca.getText().trim();
        String proprietario = txtProprietario.getText().trim();
        
        JOptionPane.showConfirmDialog(this, "Placa: "+ placa + " -  N°: "+placa.length());

        if (proprietario.equals("") && placa.length() <= 1) {
            VeiculoDAO.recuperarVeiculo("","");
        } else {
            if (proprietario.length() > 0 && placa.length() <= 1) {
                VeiculoDAO.recuperarVeiculo(txtProprietario.getText().trim(), "");
            }
            else{
                if(proprietario.equals("") && placa.length() > 0 ){
                    VeiculoDAO.recuperarVeiculo("", placa);
                }else{
                    VeiculoDAO.recuperarVeiculo(txtProprietario.getText().trim(), placa);
                }            
            }
        }
        dimensionarTabela();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnGerarOSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarOSMouseEntered
        btnGerarOS.setBackground(new Color(33, 126, 56));
        btnGerarOS.setForeground(new Color(255, 255, 255));
        btnGerarOS.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnGerarOSMouseEntered

    private void btnGerarOSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerarOSMouseExited
        btnGerarOS.setBackground(new Color(40, 167, 69));
        btnGerarOS.setForeground(new Color(255, 255, 255));
        btnGerarOS.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnGerarOSMouseExited

    private void btnGerarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarOSActionPerformed
        GerarOS();
    }//GEN-LAST:event_btnGerarOSActionPerformed

    private void preencherTabela() {
        if (tblVeiculo.getSelectedRow() > -1) {
            tblVeiculo.removeRowSelectionInterval(tblVeiculo.getSelectedRow(), tblVeiculo.getSelectedRow());
        }
        txtProprietario.setText("");
        VeiculoDAO.recuperarVeiculo("","");
        dimensionarTabela();
    }

    private void GerarOS() {
        if (tblVeiculo.getRowCount() > 0) {
            if (tblVeiculo.getSelectedRow() > -1) {
                int linha = tblVeiculo.getSelectedRow();
                int id = Integer.parseInt(tblVeiculo.getValueAt(linha, 0).toString());

                Veiculo veiculo = OrdemServicoDAO.PesquisarVeiculoVeiculo("", id);

                if (veiculo.getVei_Cod() > 0) {
                    FrmGerarOrcamento gerarOrcamento = new FrmGerarOrcamento(veiculo, origem);
                    JDesktopPanePrincipall.add(gerarOrcamento);
                    gerarOrcamento.setVisible(true);
                    gerarOrcamento.setPosicao();
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um veículo na tabela abaixo.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há registro na tabela..");
        }
    }

    private void excluir() {
        if (tblVeiculo.getRowCount() > 0) {
            if (tblVeiculo.getSelectedRow() > -1) {
                int linha = tblVeiculo.getSelectedRow();
                int id = Integer.parseInt(tblVeiculo.getValueAt(linha, 0).toString());
                String nome = tblVeiculo.getValueAt(linha, 1).toString();

                int ok = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja excluir"
                        + " cliente " + nome + "?", "Aviso", JOptionPane.YES_NO_OPTION);

                if (ok == 0) {
                    ClienteDAO.excluir(id);
                    ClienteDAO.listarCliente("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione o cliente na tabela abaixo para ser excluído.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há registro na tabela para ser excluído.");
        }
    }
    
    private void dimensionarTabela(){
        int altura = 20 * tblVeiculo.getRowCount();
        tblVeiculo.setPreferredSize(new java.awt.Dimension(840, altura));        
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarOS;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPaneVeiculo;
    private javax.swing.JFormattedTextField jtxtPlaca;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlPrincipal;
    public static javax.swing.JTable tblVeiculo;
    private javax.swing.JTextField txtProprietario;
    // End of variables declaration//GEN-END:variables
}
