package formularios;

import ClassesDao.PecaDAO;
import Formatadores.LetrasMaiusculas;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author João Carlos Batista
 */
public class FrmListaPeca extends javax.swing.JInternalFrame {

    FrmUsuario usuariocad;

    public FrmListaPeca() {
        initComponents();
        txtDescricao.setDocument(new LetrasMaiusculas());
        tblPeca.getColumnModel().getColumn(0).setMinWidth(0);
        tblPeca.getColumnModel().getColumn(0).setMaxWidth(0);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPanePeca = new javax.swing.JScrollPane();
        tblPeca = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Consulta de peças");
        setPreferredSize(new java.awt.Dimension(590, 432));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(570, 432));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        pnlCabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Consulta de Peça", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        pnlCabecalho.setPreferredSize(new java.awt.Dimension(860, 110));
        pnlCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição");
        lblDescricao.setName("lblDescricao"); // NOI18N
        pnlCabecalho.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(51, 51, 51));
        txtDescricao.setName("txtDescricao"); // NOI18N
        pnlCabecalho.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, -1));

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_P.png"))); // NOI18N
        btnPesquisar.setToolTipText("Pesquisar");
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_M.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 41, -1, -1));

        pnlPrincipal.add(pnlCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 100));

        jScrollPanePeca.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPanePeca.setAutoscrolls(true);
        jScrollPanePeca.setName("jScrollPanePeca"); // NOI18N
        jScrollPanePeca.setPreferredSize(new java.awt.Dimension(550, 170));

        tblPeca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblPeca.setForeground(new java.awt.Color(51, 51, 51));
        tblPeca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Código", "Peça", "Estoque", "Valor (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPeca.setGridColor(new java.awt.Color(255, 255, 255));
        tblPeca.setName("tblPeca"); // NOI18N
        tblPeca.setPreferredSize(new java.awt.Dimension(550, 170));
        jScrollPanePeca.setViewportView(tblPeca);
        if (tblPeca.getColumnModel().getColumnCount() > 0) {
            tblPeca.getColumnModel().getColumn(0).setResizable(false);
            tblPeca.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblPeca.getColumnModel().getColumn(1).setResizable(false);
            tblPeca.getColumnModel().getColumn(1).setPreferredWidth(350);
            tblPeca.getColumnModel().getColumn(2).setResizable(false);
            tblPeca.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblPeca.getColumnModel().getColumn(3).setResizable(false);
            tblPeca.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        pnlPrincipal.add(jScrollPanePeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 550, 170));

        btnNovo.setBackground(new java.awt.Color(0, 123, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.setBorderPainted(false);
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.setPreferredSize(new java.awt.Dimension(90, 40));
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoMouseExited(evt);
            }
        });
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        btnAlterar.setBackground(new java.awt.Color(40, 167, 69));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setName("btnAlterar"); // NOI18N
        btnAlterar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        btnExcluir.setBackground(new java.awt.Color(220, 53, 69));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.setPreferredSize(new java.awt.Dimension(90, 40));
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirMouseExited(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        if (txtDescricao.equals("")) {
            PecaDAO.listarPeca("");
        } else {
            PecaDAO.listarPeca(txtDescricao.getText().trim());
        }
        dimensionarTabela();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        FrmPeca peca = new FrmPeca(0);
        frmMenuPrincipal.JDesktopPanePrincipall.add(peca);
        peca.setVisible(true);
        peca.setPosicao();
        dispose();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseEntered
        btnNovo.setBackground(new Color(0, 80, 217));
        btnNovo.setForeground(new Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnNovoMouseEntered

    private void btnNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseExited
        btnNovo.setBackground(new Color(0, 123, 255));
        btnNovo.setForeground(new Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnNovoMouseExited

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        btnAlterar.setBackground(new Color(33, 126, 56));
        btnAlterar.setForeground(new Color(255, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        btnAlterar.setBackground(new Color(40, 167, 69));
        btnAlterar.setForeground(new Color(255, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        atualizar();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseEntered
        btnExcluir.setBackground(new Color(200, 35, 51));
        btnExcluir.setForeground(new Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnExcluirMouseEntered

    private void btnExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseExited
        btnExcluir.setBackground(new Color(220, 53, 69));
        btnExcluir.setForeground(new Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnExcluirMouseExited

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    public void preencherTabela() {
        if (tblPeca.getSelectedRow() > -1) {
            tblPeca.removeRowSelectionInterval(tblPeca.getSelectedRow(), tblPeca.getSelectedRow());
        }
        txtDescricao.setText("");
        PecaDAO.listarPeca("");
        dimensionarTabela();
    }

    public void atualizar() {

        if (tblPeca.getRowCount() > 0) {
            if (tblPeca.getSelectedRow() > -1) {
                int linha = tblPeca.getSelectedRow();
                int id = Integer.parseInt(tblPeca.getValueAt(linha, 0).toString());

                FrmPeca peca = new FrmPeca(id);
                frmMenuPrincipal.JDesktopPanePrincipall.add(peca);
                peca.setVisible(true);
                peca.setPosicao();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma peça na tabela abaixo.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há registro na tabela para ser atualizado.");
        }
    }

    public void excluir() {

        if (tblPeca.getRowCount() > 0) {
            if (tblPeca.getSelectedRow() > -1) {
                int linha = tblPeca.getSelectedRow();
                int id = Integer.parseInt(tblPeca.getValueAt(linha, 0).toString());
                String nome = tblPeca.getValueAt(linha, 1).toString();

                int ok = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja excluir"
                        + " a peça " + nome + "?", "Aviso", JOptionPane.YES_NO_OPTION);

                if (ok == 0) {
                    PecaDAO.excluir(id);
                    PecaDAO.listarPeca("");
                    dimensionarTabela();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione a peça na tabela abaixo para ser excluído.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há registro na tabela para ser excluído.");
        }
    }

    public void dimensionarTabela() {
        int altura = 16 * tblPeca.getRowCount();
        tblPeca.setPreferredSize(new java.awt.Dimension(550, altura));
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPanePeca;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlPrincipal;
    public static javax.swing.JTable tblPeca;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
