package formularios;

import ClassesDao.OrdemServicoDAO;
import Formatadores.LetrasMaiusculas;
import Formatadores.teclaNumerica;
import static formularios.frmMenuPrincipal.JDesktopPanePrincipall;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author João Carlos Batista
 */
public class FrmListaOrdemServico extends javax.swing.JInternalFrame {

    FrmUsuario usuariocad;

    public FrmListaOrdemServico() {
        initComponents();
        txtOSNumero.setDocument(new teclaNumerica());
        txtNome.setDocument(new LetrasMaiusculas());
        
        tblOrdemServico.getColumnModel().getColumn(0).setMinWidth(0);
        tblOrdemServico.getColumnModel().getColumn(0).setMaxWidth(0);        
        
        preencherTabela();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        lblOSNumero = new javax.swing.JLabel();
        txtOSNumero = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPaneOrdemServico = new javax.swing.JScrollPane();
        tblOrdemServico = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Consultar de ordem de serviço");
        setPreferredSize(new java.awt.Dimension(980, 500));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(900, 500));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        pnlCabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Consultar Ordem de Serviço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        pnlCabecalho.setForeground(new java.awt.Color(51, 51, 51));
        pnlCabecalho.setPreferredSize(new java.awt.Dimension(935, 110));
        pnlCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOSNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblOSNumero.setText("O.S N°");
        lblOSNumero.setName("lblOSNumero"); // NOI18N
        pnlCabecalho.add(lblOSNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        txtOSNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtOSNumero.setForeground(new java.awt.Color(51, 51, 51));
        txtOSNumero.setName("txtOSNumero"); // NOI18N
        txtOSNumero.setPreferredSize(new java.awt.Dimension(130, 25));
        pnlCabecalho.add(txtOSNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 130, -1));

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setText("Proprietário");
        lblNome.setName("lblNome"); // NOI18N
        pnlCabecalho.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 30, -1, -1));

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(51, 51, 51));
        txtNome.setName("txtNome"); // NOI18N
        txtNome.setPreferredSize(new java.awt.Dimension(290, 25));
        pnlCabecalho.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 50, 290, -1));

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_P.png"))); // NOI18N
        btnPesquisar.setToolTipText("");
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_M.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 40, -1, -1));

        pnlPrincipal.add(pnlCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, 935, 100));

        jScrollPaneOrdemServico.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneOrdemServico.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneOrdemServico.setAutoscrolls(true);
        jScrollPaneOrdemServico.setName("jScrollPaneOrdemServico"); // NOI18N
        jScrollPaneOrdemServico.setPreferredSize(new java.awt.Dimension(935, 240));

        tblOrdemServico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblOrdemServico.setForeground(new java.awt.Color(51, 51, 51));
        tblOrdemServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "OS N°", "Proprietário", "Veículo", "Placa", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrdemServico.setGridColor(new java.awt.Color(255, 255, 255));
        tblOrdemServico.setName("tblOrdemServico"); // NOI18N
        tblOrdemServico.setPreferredSize(new java.awt.Dimension(915, 140));
        jScrollPaneOrdemServico.setViewportView(tblOrdemServico);
        if (tblOrdemServico.getColumnModel().getColumnCount() > 0) {
            tblOrdemServico.getColumnModel().getColumn(0).setResizable(false);
            tblOrdemServico.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblOrdemServico.getColumnModel().getColumn(1).setResizable(false);
            tblOrdemServico.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblOrdemServico.getColumnModel().getColumn(2).setResizable(false);
            tblOrdemServico.getColumnModel().getColumn(2).setPreferredWidth(315);
            tblOrdemServico.getColumnModel().getColumn(3).setResizable(false);
            tblOrdemServico.getColumnModel().getColumn(3).setPreferredWidth(300);
            tblOrdemServico.getColumnModel().getColumn(4).setResizable(false);
            tblOrdemServico.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblOrdemServico.getColumnModel().getColumn(5).setResizable(false);
            tblOrdemServico.getColumnModel().getColumn(5).setPreferredWidth(140);
        }

        pnlPrincipal.add(jScrollPaneOrdemServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 200, 935, -1));

        btnNovo.setBackground(new java.awt.Color(0, 123, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.setBorderPainted(false);
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.setPreferredSize(new java.awt.Dimension(90, 40));
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoMouseExited(evt);
            }
        });
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 135, 100, -1));

        btnAlterar.setBackground(new java.awt.Color(40, 167, 69));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setName("btnAlterar"); // NOI18N
        btnAlterar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 135, 100, -1));

        btnCancelar.setBackground(new java.awt.Color(220, 53, 69));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 135, 100, -1));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if(txtOSNumero.getText().trim().equals("")){
            OrdemServicoDAO.listarOrdemServico(0, txtNome.getText().trim());
        }else{
            OrdemServicoDAO.listarOrdemServico(Integer.parseInt(txtOSNumero.getText()), txtNome.getText().trim());
        }        
        dimensionarTabela();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        /*FrmLocalizarPlacaOrcamento gerarOS = new FrmLocalizarPlacaOrcamento("S");
        frmMenuPrincipal.JDesktopPanePrincipall.add(gerarOS);
        gerarOS.setVisible(true);
        gerarOS.setPosicao();*/
        FrmListarVeiculo listarVeiculo = new FrmListarVeiculo("S");
        JDesktopPanePrincipall.add(listarVeiculo);
        listarVeiculo.setVisible(true);
        listarVeiculo.setPosicao();      
        dispose();        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseEntered
        btnNovo.setBackground(new Color(0, 80, 217));
        btnNovo.setForeground(new Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnNovoMouseEntered

    private void btnNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseExited
        btnNovo.setBackground(new Color(0, 123, 255));
        btnNovo.setForeground(new Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnNovoMouseExited

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        btnAlterar.setBackground(new Color(33, 126, 56));
        btnAlterar.setForeground(new Color(255, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        btnAlterar.setBackground(new Color(40, 167, 69));
        btnAlterar.setForeground(new Color(255, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        atualizar();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        btnCancelar.setBackground(new Color(200, 35, 51));
        btnCancelar.setForeground(new Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        btnCancelar.setBackground(new Color(220, 53, 69));
        btnCancelar.setForeground(new Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void preencherTabela() {
        if (tblOrdemServico.getSelectedRow() > -1) {
            tblOrdemServico.removeRowSelectionInterval(tblOrdemServico.getSelectedRow(), tblOrdemServico.getSelectedRow());
        }
        txtNome.setText("");        
        OrdemServicoDAO.listarOrdemServico(0, "");        
        dimensionarTabela();    
    }
    
    private void atualizar() {
        if (tblOrdemServico.getRowCount() > 0) {
            if (tblOrdemServico.getSelectedRow() > -1) {
                int linha = tblOrdemServico.getSelectedRow();
                int id = Integer.parseInt(tblOrdemServico.getValueAt(linha, 0).toString());

                FrmOrdemServico ordemServico = new FrmOrdemServico(id);
                frmMenuPrincipal.JDesktopPanePrincipall.add(ordemServico);
                ordemServico.setVisible(true);
                ordemServico.setPosicao();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione uma O.S na tabela abaixo.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há registro na tabela para ser atualizado.");
        }
    }

    private void cancelar() {
        if (tblOrdemServico.getRowCount() > 0) {
            if (tblOrdemServico.getSelectedRow() > -1) {
                int linha = tblOrdemServico.getSelectedRow();
                int id = Integer.parseInt(tblOrdemServico.getValueAt(linha, 0).toString());
                String OSnumero = tblOrdemServico.getValueAt(linha, 0).toString();

                int ok = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja cancelar"
                        + " a O.S " + OSnumero + "?", "Aviso", JOptionPane.YES_NO_OPTION);

                if (ok == 0) {
                    OrdemServicoDAO.cancelarOrdemServico(id);
                    OrdemServicoDAO.listarOrdemServico(0, "");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione a O.S na tabela abaixo para cancelar.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há registro na tabela para ser cancelado.");
        }
    }
    
    private void dimensionarTabela(){
        int altura = 20 * tblOrdemServico.getRowCount();
        tblOrdemServico.setPreferredSize(new java.awt.Dimension(840, altura));    
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPaneOrdemServico;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOSNumero;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlPrincipal;
    public static javax.swing.JTable tblOrdemServico;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtOSNumero;
    // End of variables declaration//GEN-END:variables
}