
package formularios;

import java.awt.Toolkit;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
/**
 *
 * @author João Carlos Batista
 */
public class frmMenuPrincipalBackup extends javax.swing.JFrame {
    
    /*public boolean estaFechado(Object obj){
        JInternalFrame[] ativo = carregador.getAllFrames();
        boolean fechado = true;
        
        int i = 0;
        
        while(i < ativo.length && fechado ){
            if(ativo[i] == obj){
                fechado = false;
            }
            i++;
        }
        
        return  fechado;
    }*/
    
    
    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipalBackup() {
        initComponents();                                
        setIcon();        
        
        /*JDesktopPanel = new JDesktopPane(){        
            @Override
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                g.setColor(new java.awt.Color(255, 255, 255));
                g.fillRect(0, 0, getWidth(), getHeight());
                
            }
        };*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnOrcamento = new javax.swing.JButton();
        btnOrdemServico = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        btnServico = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/principal/fundo.png"));
        Image image = icon.getImage();
        JDesktopPanePrincipall = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gerenciamento de oficina mecânica V1.0 - 2018");
        setBackground(new java.awt.Color(255, 255, 255));
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setName("pnlPrincipal"); // NOI18N
        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        pnlCabecalho.setBackground(new java.awt.Color(0, 119, 155));
        pnlCabecalho.setName("pnlCabecalho"); // NOI18N
        pnlCabecalho.setPreferredSize(new java.awt.Dimension(1200, 70));
        pnlCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes/Client_Small.png"))); // NOI18N
        btnCliente.setText("PROPRIETÁRIO");
        btnCliente.setToolTipText("PROPRIETÁRIO");
        btnCliente.setBorder(null);
        btnCliente.setContentAreaFilled(false);
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.setName("btnCliente"); // NOI18N
        btnCliente.setPreferredSize(new java.awt.Dimension(90, 60));
        btnCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes/Client_Medium.png"))); // NOI18N
        btnCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        btnOrcamento.setBackground(new java.awt.Color(255, 255, 255));
        btnOrcamento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOrcamento.setForeground(new java.awt.Color(255, 255, 255));
        btnOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/orcamento/budget_Small.png"))); // NOI18N
        btnOrcamento.setText("ORÇAMENTO");
        btnOrcamento.setToolTipText("ORÇAMENTO");
        btnOrcamento.setBorder(null);
        btnOrcamento.setContentAreaFilled(false);
        btnOrcamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrcamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrcamento.setName("btnOrcamento"); // NOI18N
        btnOrcamento.setPreferredSize(new java.awt.Dimension(70, 60));
        btnOrcamento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/orcamento/budget_Medium.png"))); // NOI18N
        btnOrcamento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrcamentoActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 6, -1, -1));

        btnOrdemServico.setBackground(new java.awt.Color(255, 255, 255));
        btnOrdemServico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOrdemServico.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdemServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/servico/tools_Small.png"))); // NOI18N
        btnOrdemServico.setText("ORDEM SERVIÇO");
        btnOrdemServico.setToolTipText("SERVIÇO");
        btnOrdemServico.setBorder(null);
        btnOrdemServico.setContentAreaFilled(false);
        btnOrdemServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrdemServico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrdemServico.setName("btnOrdemServico"); // NOI18N
        btnOrdemServico.setPreferredSize(new java.awt.Dimension(54, 60));
        btnOrdemServico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/servico/tools_Medium.png"))); // NOI18N
        btnOrdemServico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdemServicoActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnOrdemServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 6, 100, -1));

        btnEstoque.setBackground(new java.awt.Color(255, 255, 255));
        btnEstoque.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEstoque.setForeground(new java.awt.Color(255, 255, 255));
        btnEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/peca/stock_Small.png"))); // NOI18N
        btnEstoque.setText("ESTOQUE");
        btnEstoque.setToolTipText("ESTOQUE");
        btnEstoque.setBorder(null);
        btnEstoque.setContentAreaFilled(false);
        btnEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstoque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstoque.setName("btnEstoque"); // NOI18N
        btnEstoque.setPreferredSize(new java.awt.Dimension(54, 60));
        btnEstoque.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/peca/stock_Medium.png"))); // NOI18N
        btnEstoque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 6, -1, -1));

        btnServico.setBackground(new java.awt.Color(255, 255, 255));
        btnServico.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnServico.setForeground(new java.awt.Color(255, 255, 255));
        btnServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/servico/tools_Small.png"))); // NOI18N
        btnServico.setText("SERVIÇO");
        btnServico.setToolTipText("SERVIÇO");
        btnServico.setBorder(null);
        btnServico.setContentAreaFilled(false);
        btnServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServico.setName("btnServico"); // NOI18N
        btnServico.setPreferredSize(new java.awt.Dimension(54, 60));
        btnServico.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/servico/tools_Medium.png"))); // NOI18N
        btnServico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicoActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 6, -1, -1));

        btnUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/add-user_Small.png"))); // NOI18N
        btnUsuario.setText("USUÁRIO");
        btnUsuario.setToolTipText("USUÁRIO");
        btnUsuario.setBorder(null);
        btnUsuario.setContentAreaFilled(false);
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setName("btnUsuario"); // NOI18N
        btnUsuario.setPreferredSize(new java.awt.Dimension(54, 60));
        btnUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios/add-user_Medium.png"))); // NOI18N
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 6, -1, -1));

        pnlPrincipal.add(pnlCabecalho, java.awt.BorderLayout.PAGE_START);

        JDesktopPanePrincipall.setBackground(new java.awt.Color(255, 255, 255));
        JDesktopPanePrincipall.setForeground(new java.awt.Color(255, 255, 255));
        JDesktopPanePrincipall.setName("JDesktopPanePrincipall"); // NOI18N
        JDesktopPanePrincipall.setOpaque(false);
        JDesktopPanePrincipall.setPreferredSize(new java.awt.Dimension(800, 500));
        pnlPrincipal.add(JDesktopPanePrincipall, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlPrincipal);

        setSize(new java.awt.Dimension(730, 415));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrcamentoActionPerformed
    
        FrmLocalizarPlacaOrcamento localizarPlacaOrcamento = new FrmLocalizarPlacaOrcamento("O");   
        JDesktopPanePrincipall.add(localizarPlacaOrcamento);
        localizarPlacaOrcamento.setVisible(true);
        localizarPlacaOrcamento.setPosicao();        

    }//GEN-LAST:event_btnOrcamentoActionPerformed
    
   FrmCliente_OLD cliente;
    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        
        FrmListaCliente Listacliente = new FrmListaCliente();        
        JDesktopPanePrincipall.add(Listacliente);
        Listacliente.setVisible(true);
        Listacliente.setPosicao();
        /*
        if(estaFechado(cliente)){
            cliente = new FrmCliente_OLD();
            carregador.add(cliente).setLocation(150,3);         
            cliente.show();        
        }
        else{           
             cliente.toFront(); 
             cliente.show();
        }
        */
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed

        FrmListaUsuario listaUsuario = new FrmListaUsuario();
        
        JDesktopPanePrincipall.add(listaUsuario)  ;
        listaUsuario.setVisible(true);
        listaUsuario.setPosicao();
        /* if(estaFechado(listaUsuario)){
            listaUsuario = new frmListaUsuario();
            //carregador.add(listaUsuario).setLocation(150,3);         
            listaUsuario.show();        
        }
        else{           
             listaUsuario.toFront(); 
             listaUsuario.show();
        }*/
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
        
        FrmListaPeca ListaPeca = new FrmListaPeca();
        JDesktopPanePrincipall.add(ListaPeca);
        ListaPeca.setVisible(true);
        ListaPeca.setPosicao();
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicoActionPerformed

        FrmListaServico ListaServico = new FrmListaServico();
        JDesktopPanePrincipall.add(ListaServico);
        ListaServico.setVisible(true);
        ListaServico.setPosicao();        
    }//GEN-LAST:event_btnServicoActionPerformed

    private void btnOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdemServicoActionPerformed
        FrmListaOrdemServico listarOrdemServiço = new FrmListaOrdemServico();   
        JDesktopPanePrincipall.add(listarOrdemServiço);
        listarOrdemServiço.setVisible(true);
        listarOrdemServiço.setPosicao();  
    }//GEN-LAST:event_btnOrdemServicoActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) { //Nimbus
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipalBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipalBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipalBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipalBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmMenuPrincipalBackup tela = new frmMenuPrincipalBackup();
                tela.setLocationRelativeTo(null);                
                tela.setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/icons/mechanic.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane JDesktopPanePrincipall;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnOrcamento;
    private javax.swing.JButton btnOrdemServico;
    private javax.swing.JButton btnServico;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
