package formularios;

import Classes.Cliente;
import ClassesDao.ClienteDAO;
import ClassesDao.VeiculoDAO;
import ClassesEnum.Pessoas;
import Formatadores.CNPJ;
import Formatadores.CPF;
import Formatadores.FormatadorMascara;
import GeradorID.gerarId;
import Formatadores.LetrasMaiusculas;
import Formatadores.TeclasPermitidasCnpj;
import Formatadores.TeclasPermitidasCpf;
import Formatadores.TeclasPermitidasTelCel;
import Formatadores.TeclasPermitidasTelRes;
import static formularios.FrmListaCliente.tblCliente;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static formularios.frmMenuPrincipal.JDesktopPanePrincipall;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author João Carlos Batista
 */
public class FrmProprietarioVeiculo extends javax.swing.JInternalFrame {

    private String documento;
    private String docAuxi;
    private int idAlteracao = 0;
    private String mensagem;
    private String telaOrigem; //M = Menu Principal - V = Veículo

    public FrmProprietarioVeiculo(int id, String tela) {
        initComponents();
        txtNome.setDocument(new LetrasMaiusculas());
        txtEndereco.setDocument(new LetrasMaiusculas());
        txtBairro.setDocument(new LetrasMaiusculas());
        txtEmail.setDocument(new LetrasMaiusculas());
        txtPlaca.setDocument(new LetrasMaiusculas());
        txtTelResidencial.setDocument(new TeclasPermitidasTelRes());
        txtTelCelular.setDocument(new TeclasPermitidasTelCel());
        cmbTpPes.setModel(new DefaultComboBoxModel(Pessoas.values()));
        this.idAlteracao = id;
        this.telaOrigem = tela;
        tratarTipoPessoa();

        if (telaOrigem == "M") {
            jTabbedPaneProprietario.setSelectedIndex(0); //Menu Principal
        } else {
            jTabbedPaneProprietario.setSelectedIndex(1); //Cadastro de Veículos
        }

        if (idAlteracao > 0) {
            carregarCliente(this.idAlteracao);
        }

        cmbTpPes.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {

                tratarTipoPessoa();
            }
        });
        tblVeiculo.getColumnModel().getColumn(0).setMinWidth(0);
        tblVeiculo.getColumnModel().getColumn(0).setMaxWidth(0);
        preencherTabela(this.idAlteracao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneProprietario = new javax.swing.JTabbedPane();
        jPanelPai = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTipPes = new javax.swing.JLabel();
        cmbTpPes = new javax.swing.JComboBox<>();
        lblEndereco = new javax.swing.JLabel();
        lblCpf_Cnpj = new javax.swing.JLabel();
        txtCpf_Cnpj = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblTelResidencial = new javax.swing.JLabel();
        txtTelResidencial = new javax.swing.JTextField();
        lblTelCelular = new javax.swing.JLabel();
        txtTelCelular = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pnlVeiculo = new javax.swing.JPanel();
        pnlPrincipalVeiculo = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPaneVeiculo = new javax.swing.JScrollPane();
        tblVeiculo = new javax.swing.JTable();

        setTitle("Cadastro de proprietário / veículo");
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(575, 402));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPaneProprietario.setForeground(new java.awt.Color(51, 51, 51));
        jTabbedPaneProprietario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTabbedPaneProprietario.setPreferredSize(new java.awt.Dimension(575, 391));

        jPanelPai.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(530, 360));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setText("Nome");
        lblNome.setName("lblNome"); // NOI18N
        pnlPrincipal.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(51, 51, 51));
        txtNome.setName("txtNome"); // NOI18N
        txtNome.setPreferredSize(new java.awt.Dimension(360, 25));
        pnlPrincipal.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 360, 25));

        lblTipPes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTipPes.setText("Tipo de pessoa");
        lblTipPes.setName("lblTipPes"); // NOI18N
        pnlPrincipal.add(lblTipPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 30, -1, -1));

        cmbTpPes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbTpPes.setForeground(new java.awt.Color(51, 51, 51));
        cmbTpPes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Pessoa", "Física", "Jurídica" }));
        cmbTpPes.setName("cmbTpPes"); // NOI18N
        cmbTpPes.setPreferredSize(new java.awt.Dimension(140, 25));
        cmbTpPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTpPesActionPerformed(evt);
            }
        });
        pnlPrincipal.add(cmbTpPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 50, 140, -1));

        lblEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço");
        lblEndereco.setName("lblEndereco"); // NOI18N
        pnlPrincipal.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, -1, -1));

        lblCpf_Cnpj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCpf_Cnpj.setText("CPF/CNPJ");
        lblCpf_Cnpj.setName("lblCpf_Cnpj"); // NOI18N
        pnlPrincipal.add(lblCpf_Cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, -1, -1));

        txtCpf_Cnpj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCpf_Cnpj.setForeground(new java.awt.Color(51, 51, 51));
        txtCpf_Cnpj.setName("txtCpf_Cnpj"); // NOI18N
        txtCpf_Cnpj.setPreferredSize(new java.awt.Dimension(160, 25));
        txtCpf_Cnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpf_CnpjFocusLost(evt);
            }
        });
        txtCpf_Cnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpf_CnpjKeyPressed(evt);
            }
        });
        pnlPrincipal.add(txtCpf_Cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 160, -1));

        txtEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEndereco.setForeground(new java.awt.Color(51, 51, 51));
        txtEndereco.setName("txtEndereco"); // NOI18N
        txtEndereco.setPreferredSize(new java.awt.Dimension(310, 25));
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 170, 310, -1));

        lblBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBairro.setText("Bairro");
        lblBairro.setName("lblBairro"); // NOI18N
        pnlPrincipal.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 150, -1, -1));

        txtBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtBairro.setForeground(new java.awt.Color(51, 51, 51));
        txtBairro.setName("txtBairro"); // NOI18N
        txtBairro.setPreferredSize(new java.awt.Dimension(190, 25));
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 170, 190, -1));

        lblTelResidencial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTelResidencial.setText("Tel. Residencial");
        lblTelResidencial.setName("lblTelResidencial"); // NOI18N
        pnlPrincipal.add(lblTelResidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 210, -1, -1));

        txtTelResidencial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelResidencial.setForeground(new java.awt.Color(51, 51, 51));
        txtTelResidencial.setName("txtTelResidencial"); // NOI18N
        txtTelResidencial.setPreferredSize(new java.awt.Dimension(120, 25));
        txtTelResidencial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelResidencialFocusLost(evt);
            }
        });
        txtTelResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelResidencialActionPerformed(evt);
            }
        });
        txtTelResidencial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelResidencialKeyPressed(evt);
            }
        });
        pnlPrincipal.add(txtTelResidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, 120, -1));

        lblTelCelular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTelCelular.setText("Tel. Celular");
        lblTelCelular.setName("lblTelCelular"); // NOI18N
        pnlPrincipal.add(lblTelCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 210, -1, -1));

        txtTelCelular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelCelular.setForeground(new java.awt.Color(51, 51, 51));
        txtTelCelular.setName("txtTelCelular"); // NOI18N
        txtTelCelular.setPreferredSize(new java.awt.Dimension(120, 25));
        txtTelCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelCelularFocusLost(evt);
            }
        });
        txtTelCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelCelularActionPerformed(evt);
            }
        });
        txtTelCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelCelularKeyPressed(evt);
            }
        });
        pnlPrincipal.add(txtTelCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 230, 120, -1));

        btnFechar.setBackground(new java.awt.Color(249, 105, 14));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("Fechar");
        btnFechar.setBorderPainted(false);
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.setName("btnFechar"); // NOI18N
        btnFechar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFecharMouseExited(evt);
            }
        });
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 285, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(1, 50, 67));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 285, -1, -1));

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setName("lblEmail"); // NOI18N
        pnlPrincipal.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 210, -1, -1));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        txtEmail.setName("txtEmail"); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(240, 25));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 230, 240, -1));

        jPanelPai.add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 340));

        jTabbedPaneProprietario.addTab("Proprietário", jPanelPai);

        pnlVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        pnlVeiculo.setName("pnlVeiculo"); // NOI18N
        pnlVeiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipalVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipalVeiculo.setName("pnlPrincipalVeiculo"); // NOI18N
        pnlPrincipalVeiculo.setPreferredSize(new java.awt.Dimension(900, 500));
        pnlPrincipalVeiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        pnlCabecalho.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Localizar veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N
        pnlCabecalho.setForeground(new java.awt.Color(51, 51, 51));
        pnlCabecalho.setPreferredSize(new java.awt.Dimension(530, 110));
        pnlCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPlaca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPlaca.setText("Placa");
        lblPlaca.setName("lblNome"); // NOI18N
        pnlCabecalho.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(51, 51, 51));
        txtPlaca.setName("txtPlaca"); // NOI18N
        txtPlaca.setPreferredSize(new java.awt.Dimension(150, 25));
        pnlCabecalho.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        btnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_P.png"))); // NOI18N
        btnPesquisar.setToolTipText("");
        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/search_M.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        pnlCabecalho.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        pnlPrincipalVeiculo.add(pnlCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 90));

        btnNovo.setBackground(new java.awt.Color(0, 123, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("");
        btnNovo.setBorderPainted(false);
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.setName("btnNovo"); // NOI18N
        btnNovo.setPreferredSize(new java.awt.Dimension(90, 40));
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoMouseExited(evt);
            }
        });
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        pnlPrincipalVeiculo.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 115, -1, -1));

        btnAlterar.setBackground(new java.awt.Color(40, 167, 69));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("");
        btnAlterar.setBorderPainted(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setName("btnAlterar"); // NOI18N
        btnAlterar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlPrincipalVeiculo.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 115, -1, -1));

        btnExcluir.setBackground(new java.awt.Color(220, 53, 69));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setName("btnExcluir"); // NOI18N
        btnExcluir.setPreferredSize(new java.awt.Dimension(90, 40));
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirMouseExited(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        pnlPrincipalVeiculo.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 115, -1, -1));

        jScrollPaneVeiculo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPaneVeiculo.setName("jScrollPaneVeiculo"); // NOI18N
        jScrollPaneVeiculo.setPreferredSize(new java.awt.Dimension(570, 240));

        tblVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblVeiculo.setForeground(new java.awt.Color(51, 51, 51));
        tblVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Placa", "Fabricante", "Modelo", "Ano Fab."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVeiculo.setGridColor(new java.awt.Color(255, 255, 255));
        tblVeiculo.setName("tblVeiculo"); // NOI18N
        tblVeiculo.setPreferredSize(new java.awt.Dimension(540, 240));
        tblVeiculo.setRowHeight(20);
        tblVeiculo.setRowMargin(2);
        jScrollPaneVeiculo.setViewportView(tblVeiculo);
        if (tblVeiculo.getColumnModel().getColumnCount() > 0) {
            tblVeiculo.getColumnModel().getColumn(0).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblVeiculo.getColumnModel().getColumn(1).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(1).setPreferredWidth(95);
            tblVeiculo.getColumnModel().getColumn(2).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(2).setPreferredWidth(180);
            tblVeiculo.getColumnModel().getColumn(3).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(3).setPreferredWidth(180);
            tblVeiculo.getColumnModel().getColumn(4).setResizable(false);
            tblVeiculo.getColumnModel().getColumn(4).setPreferredWidth(75);
        }

        pnlPrincipalVeiculo.add(jScrollPaneVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 530, 160));

        pnlVeiculo.add(pnlPrincipalVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 340));

        jTabbedPaneProprietario.addTab("Veículo", pnlVeiculo);

        getContentPane().add(jTabbedPaneProprietario);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTpPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTpPesActionPerformed

    }//GEN-LAST:event_cmbTpPesActionPerformed

    private void txtCpf_CnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpf_CnpjFocusLost

        documento = txtCpf_Cnpj.getText();
        if (!documento.isEmpty()) {
            if (docAuxi != documento) {
                if (cmbTpPes.getSelectedIndex() == 1) {
                    CPF pf = new CPF(documento);
                    if (pf.isCPF()) {
                        txtCpf_Cnpj.setText(pf.getCPF(true));
                        docAuxi = txtCpf_Cnpj.getText();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "CPF inválido!");
                    }
                } else {
                    if (cmbTpPes.getSelectedIndex() == 2) {
                        CNPJ pj = new CNPJ(documento);
                        if (pj.isCNPJ()) {
                            txtCpf_Cnpj.setText(pj.getCNPJ(true));
                            docAuxi = txtCpf_Cnpj.getText();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "CNPJ inválido!");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_txtCpf_CnpjFocusLost

    private void txtCpf_CnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpf_CnpjKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpf_CnpjKeyPressed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void btnFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseEntered
        btnFechar.setBackground(new Color(249, 105, 40));
        btnFechar.setForeground(Color.WHITE);
        btnFechar.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnFecharMouseEntered

    private void btnFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseExited
        btnFechar.setBackground(new Color(249, 105, 14));
        btnFechar.setForeground(Color.WHITE);
        btnFechar.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnFecharMouseExited

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        /*
        String msg = "Alterações não salvas serão perdidas.\n Deseja realmente sair sem salvar as alterações";
        int ok = JOptionPane.showConfirmDialog(null, msg, "Aviso", JOptionPane.YES_NO_OPTION);

        if (ok == 0) {
            FrmListaCliente listaCliente = new FrmListaCliente();
            JDesktopPanePrincipall.add(listaCliente);
            listaCliente.setVisible(true);
            listaCliente.setPosicao();
            dispose();
        }*/
        FrmListaCliente listaCliente = new FrmListaCliente();
        JDesktopPanePrincipall.add(listaCliente);
        listaCliente.setVisible(true);
        listaCliente.setPosicao();
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        btnSalvar.setBackground(new Color(1, 50, 90));////(58, 83, 155));
        btnSalvar.setForeground(Color.WHITE);
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 16));
        //passa o mouse em cima
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        btnSalvar.setBackground(new Color(1, 50, 67));
        btnSalvar.setForeground(Color.WHITE);
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14));
        //hora que o mouse sai de cima
    }//GEN-LAST:event_btnSalvarMouseExited

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (camposObrigatorios()) {
            JOptionPane.showMessageDialog(this, mensagem, "Alerta", 0,
                    new ImageIcon(getClass().getResource("/imagens/icons/info_P.png")));
        } else {
            Cliente cliente = new Cliente();
            cliente.setCli_Nom(txtNome.getText());
            cliente.setCli_Tip_Pes(cmbTpPes.getSelectedItem().toString());
            cliente.setCli_Cpf_Cnpj(txtCpf_Cnpj.getText());
            cliente.setCli_End(txtEndereco.getText());
            cliente.setCli_Bai(txtBairro.getText());
            cliente.setCli_Tel_Res(txtTelResidencial.getText());
            cliente.setCli_Tel_Cel(txtTelCelular.getText());
            cliente.setCli_Ema(txtEmail.getText());
            if (this.idAlteracao > 0) {
                cliente.setCli_Cod(this.idAlteracao);
                ClienteDAO.alterarCliente(cliente);
            } else {
                cliente.setCli_Cod(gerarId.gerarIdCliente());
                this.idAlteracao = cliente.getCli_Cod();
                ClienteDAO.gravarCliente(cliente);
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseEntered
        btnNovo.setBackground(new Color(0, 80, 217));
        btnNovo.setForeground(new Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnNovoMouseEntered

    private void btnNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseExited
        btnNovo.setBackground(new Color(0, 123, 255));
        btnNovo.setForeground(new Color(255, 255, 255));
        btnNovo.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnNovoMouseExited

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        if (idAlteracao > 0) {
            FrmVeiculo veiculo = new FrmVeiculo(0, this.idAlteracao);
            frmMenuPrincipal.JDesktopPanePrincipall.add(veiculo);
            veiculo.setVisible(true);
            veiculo.setPosicao();
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "O cliente precisa estar salvo na banco de dados\n"
                    + "antes de inserir o veículo.");
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        btnAlterar.setBackground(new Color(33, 126, 56));
        btnAlterar.setForeground(new Color(255, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        btnAlterar.setBackground(new Color(40, 167, 69));
        btnAlterar.setForeground(new Color(255, 255, 255));
        btnAlterar.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        if (tblVeiculo.getRowCount() > 0) {
            if (tblVeiculo.getSelectedRow() > -1) {
                int linha = tblVeiculo.getSelectedRow();
                int idVeiculo = Integer.parseInt(tblVeiculo.getValueAt(linha, 0).toString());

                FrmVeiculo veiculo = new FrmVeiculo(idVeiculo, idAlteracao);
                frmMenuPrincipal.JDesktopPanePrincipall.add(veiculo);
                veiculo.setVisible(true);
                veiculo.setPosicao();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Selecione o registro na tabela a ser alterado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há registro na tabela para ser atualizado.");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseEntered
        btnExcluir.setBackground(new Color(200, 35, 51));
        btnExcluir.setForeground(new Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnExcluirMouseEntered

    private void btnExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseExited
        btnExcluir.setBackground(new Color(220, 53, 69));
        btnExcluir.setForeground(new Color(255, 255, 255));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnExcluirMouseExited

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (tblVeiculo.getRowCount() > 0) {
            if (tblVeiculo.getSelectedRow() > -1) {

                int linha = tblVeiculo.getSelectedRow();
                int idVeiculo = Integer.parseInt(tblVeiculo.getValueAt(linha, 0).toString());
                String placa = tblVeiculo.getValueAt(linha, 1).toString();

                int ok = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja exluir"
                        + " o veículo de placa " + placa + "?", "Aviso", JOptionPane.YES_NO_OPTION);

                if (ok == 0) {
                    VeiculoDAO.excluirVeiculo(idVeiculo);
                    VeiculoDAO.listarVeiculo(idAlteracao, "");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione o registro na tabela a ser excluído.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não há registro na tabela para ser excluído.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        if (txtPlaca.equals("")) {
            VeiculoDAO.listarVeiculo(this.idAlteracao, "");
        } else {
            VeiculoDAO.listarVeiculo(this.idAlteracao, txtPlaca.getText());
        }
        dimensionarTabela();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtTelResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelResidencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelResidencialActionPerformed

    private void txtTelCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelCelularActionPerformed

    private void txtTelResidencialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelResidencialKeyPressed

    }//GEN-LAST:event_txtTelResidencialKeyPressed

    private void txtTelCelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelCelularKeyPressed

    }//GEN-LAST:event_txtTelCelularKeyPressed

    private void txtTelResidencialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelResidencialFocusLost
        txtTelResidencial.setText(FormatadorMascara.formatMascTelRes(txtTelResidencial.getText()));
    }//GEN-LAST:event_txtTelResidencialFocusLost

    private void txtTelCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelCelularFocusLost
        txtTelCelular.setText(FormatadorMascara.formatMascTelCel(txtTelCelular.getText()));
    }//GEN-LAST:event_txtTelCelularFocusLost

    private void tratarTipoPessoa() {
        txtCpf_Cnpj.setText("");

        if (cmbTpPes.getSelectedIndex() == 0) {
            lblCpf_Cnpj.setText("CPF/CNPJ");
            txtCpf_Cnpj.setEnabled(false);
        } else {
            if (cmbTpPes.getSelectedIndex() == 1) {
                txtCpf_Cnpj.setDocument(new TeclasPermitidasCpf());
                lblCpf_Cnpj.setText("CPF");
                txtCpf_Cnpj.setEnabled(true);
            } else {
                txtCpf_Cnpj.setDocument(new TeclasPermitidasCnpj());
                lblCpf_Cnpj.setText("CNPJ");
                txtCpf_Cnpj.setEnabled(true);
            }
        }
    }

    public void preencherTabela(int idCliente) {
        if (tblVeiculo.getSelectedRow() > -1) {
            tblVeiculo.removeRowSelectionInterval(tblVeiculo.getSelectedRow(), tblVeiculo.getSelectedRow());
        }
        txtPlaca.setText("");
        VeiculoDAO.listarVeiculo(this.idAlteracao, "");
        dimensionarTabela();
    }

    private void carregarCliente(int cod) {

        if (cod > 0) {
            Cliente cliente = ClienteDAO.carregarCliente(cod);
            txtNome.setText(cliente.getCli_Nom());
            txtEndereco.setText(cliente.getCli_End());
            txtBairro.setText(cliente.getCli_Bai());
            txtTelResidencial.setText(FormatadorMascara.formatMascTelRes(cliente.getCli_Tel_Res()));
            txtTelCelular.setText(FormatadorMascara.formatMascTelCel(cliente.getCli_Tel_Cel()));
            txtEmail.setText(cliente.getCli_Ema());

            if (cliente.getCli_Tip_Pes().equals("FÍSICA")) {
                cmbTpPes.setSelectedIndex(1);
            } else {
                if (cliente.getCli_Tip_Pes().equals("JURÍDICA")) {
                    cmbTpPes.setSelectedIndex(2);
                } else {
                    cmbTpPes.setSelectedIndex(0);
                }
            }
            tratarTipoPessoa();
            txtCpf_Cnpj.setText(cliente.getCli_Cpf_Cnpj());
        }
    }

    private boolean camposObrigatorios() {

        boolean retorno = false;
        mensagem = "Preenchimento obrigatório\n do(s) campo(s) abaixo:\n\n";

        if (txtNome.getText().equals("")) {
            mensagem += "Nome;\n";
            retorno = true;
        }

        if (cmbTpPes.getSelectedIndex() == 0) {
            mensagem += "Tipo de Pessoa;";
            retorno = true;
        }
        return retorno;
    }

    public void dimensionarTabela() {
        int altura = 20 * tblVeiculo.getRowCount();
        tblVeiculo.setPreferredSize(new java.awt.Dimension(550, altura));
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTpPes;
    private javax.swing.JPanel jPanelPai;
    private javax.swing.JScrollPane jScrollPaneVeiculo;
    private javax.swing.JTabbedPane jTabbedPaneProprietario;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCpf_Cnpj;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblTelCelular;
    private javax.swing.JLabel lblTelResidencial;
    private javax.swing.JLabel lblTipPes;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlPrincipalVeiculo;
    private javax.swing.JPanel pnlVeiculo;
    public static javax.swing.JTable tblVeiculo;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCpf_Cnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTelCelular;
    private javax.swing.JTextField txtTelResidencial;
    // End of variables declaration//GEN-END:variables

}
