package formularios;

import Classes.Peca;
import Classes.StatusRegistro;
import ClassesDao.PecaDAO;
import ClassesEnum.ServicoProduto;
import Formatadores.LetrasMaiusculas;
import Formatadores.MonetarioDocument;
import Formatadores.TeclasNumericaAno1;
import Formatadores.TratarMoeda;
import Formatadores.teclaNumerica;
import GeradorID.gerarId;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author João Carlos Batista
 */
public class FrmRelatorio extends javax.swing.JInternalFrame {

    private int idProduto = 0;
    private String mensagem;
    
    public FrmRelatorio(int id) {
        initComponents();
        txtDescricao.setDocument(new LetrasMaiusculas());
        txtArea.setDocument(new TeclasNumericaAno1());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblDescricao1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Cadastro de Peças");
        setPreferredSize(new java.awt.Dimension(596, 413));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(350, 310));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição");
        lblDescricao.setName("lblDescricao"); // NOI18N
        pnlPrincipal.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(51, 51, 51));
        txtDescricao.setName("txtDescricao"); // NOI18N
        txtDescricao.setPreferredSize(new java.awt.Dimension(305, 25));
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 410, -1));

        btnFechar.setBackground(new java.awt.Color(249, 105, 14));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("Fechar");
        btnFechar.setBorderPainted(false);
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.setName("btnFechar"); // NOI18N
        btnFechar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFecharMouseExited(evt);
            }
        });
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(1, 50, 67));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        lblDescricao1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescricao1.setText("Descrição");
        lblDescricao1.setName("lblDescricao"); // NOI18N
        pnlPrincipal.add(lblDescricao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 100, -1, -1));

        txtArea.setColumns(12);
        txtArea.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtArea.setLineWrap(true);
        txtArea.setRows(2);
        txtArea.setText("AAAAAAAAAAAAAW\nAAAAAAAAAAAA");
        txtArea.setWrapStyleWord(true);
        txtArea.setAutoscrolls(false);
        txtArea.setName("txtArea"); // NOI18N
        jScrollPane1.setViewportView(txtArea);

        pnlPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 70));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(320, 120));

        jTextArea2.setColumns(13);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(8);
        jTextArea2.setText("Mecânica em geral\nCambagem\nSuspensão - Freios - Pneus\nTel.:(12) 3913-7733 / 7820-7554 / ID 114*t4200\n7814-4580 / ID 96*66170\nRua Elza B. D'Avila, 47 - Jardim São Dimas - Sjcampos - SP\n");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setPreferredSize(new java.awt.Dimension(318, 118));
        jScrollPane2.setViewportView(jTextArea2);

        pnlPrincipal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 320, 130));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        /*
        if (camposObrigatorios()) {
            JOptionPane.showMessageDialog(this, mensagem, "Alerta", 0,
                    new ImageIcon(getClass().getResource("/imagens/icons/info_P.png")));
        } else {
            Peca produto = new Peca();
            produto.setPro_Des(txtDescricao.getText().trim());
            produto.setPro_Tip(ServicoProduto.PRODUTO.toString());
            if(txtQuantMin.getText().trim().isEmpty()){
                produto.setPro_Qua_Min(0);
            }else{
                produto.setPro_Qua_Min(Integer.parseInt(txtQuantMin.getText()));
            }
            
            if(txtQuantEstoque.getText().trim().equals("")){
                produto.setPro_Qua_Est(0);
            }else{
                produto.setPro_Qua_Est(Integer.parseInt(txtQuantEstoque.getText()));
            }
            produto.setPro_Val_Cus(TratarMoeda.Moeda(jtxtValorCusto.getText()));
            produto.setPro_Val_Ven(TratarMoeda.Moeda(jtxtValor.getText()));
            produto.setPro_Sta(StatusRegistro.ATIVO.toString());

            if (this.idProduto > 0) {
                produto.setPro_Cod(this.idProduto);
                PecaDAO.alterarProduto(produto);
            } else {
                produto.setPro_Cod(gerarId.gerarIDProdutoServico());
                this.idProduto = produto.getPro_Cod();
                PecaDAO.gravarProduto(produto);
            }
        }*/
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        btnSalvar.setBackground(new Color(1, 50, 67));
        btnSalvar.setForeground(Color.WHITE);
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14));
        //hora que o mouse sai de cima
    }//GEN-LAST:event_btnSalvarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        btnSalvar.setBackground(new Color(1, 50, 90));////(58, 83, 155));
        btnSalvar.setForeground(Color.WHITE);
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 16));
        //passa o mouse em cima
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        FrmListaPeca listaPeca = new FrmListaPeca();
        frmMenuPrincipal.JDesktopPanePrincipall.add(listaPeca);
        listaPeca.setVisible(true);
        listaPeca.setPosicao();
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseExited
        btnFechar.setBackground(new Color(249, 105, 14));
        btnFechar.setForeground(Color.WHITE);
        btnFechar.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnFecharMouseExited

    private void btnFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseEntered
        btnFechar.setBackground(new Color(249, 105, 40));
        btnFechar.setForeground(Color.WHITE);
        btnFechar.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnFecharMouseEntered

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void carregarProduto(int cod) {
        /*
        Peca produto = PecaDAO.carregarProduto(cod);

        txtDescricao.setText(produto.getPro_Des());
        txtQuantMin.setText(Integer.toString(produto.getPro_Qua_Min()));
        txtQuantEstoque.setText(Integer.toString(produto.getPro_Qua_Est()));       
        jtxtValorCusto.setText(TratarMoeda.FormatarMoeda(produto.getPro_Val_Cus()));
        jtxtValor.setText(TratarMoeda.FormatarMoeda(produto.getPro_Val_Ven()));  */
    }

    private boolean camposObrigatorios(){
        boolean retorno = false;
        mensagem = "Preenchimento obrigatório\n do campo abaixo:\n\n";
        if (txtDescricao.getText().trim().equals("")) {
            mensagem += "Descrição;\n";
            retorno = true;
        }
        return retorno;
    }    
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricao1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}
