package formularios;

import java.awt.Color;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class FrmSplashImpressao extends javax.swing.JInternalFrame {

    public FrmSplashImpressao() {
       /*
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmSplashImpressao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FrmSplashImpressao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FrmSplashImpressao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrmSplashImpressao.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        initComponents();
        jProgressBarAguarde.setIndeterminate(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        jProgressBarAguarde = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Impressão");
        setPreferredSize(new java.awt.Dimension(368, 148));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(468, 148));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/printSplash.png"))); // NOI18N
        lblDescricao.setName("lblPrintSplash"); // NOI18N
        pnlPrincipal.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 97));

        lblMensagem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(51, 51, 51));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("Aguarde, gerando relatório...");
        lblMensagem.setName("lblMensagem"); // NOI18N
        pnlPrincipal.add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 30, 220, -1));

        jProgressBarAguarde.setBackground(new java.awt.Color(0, 102, 204));
        jProgressBarAguarde.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBarAguarde.setName("jProgressBarAguarde"); // NOI18N
        pnlPrincipal.add(jProgressBarAguarde, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 70, 159, -1));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBarAguarde;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
