/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author João Carlos Batista
 */
public class FrmSplashScreen extends javax.swing.JFrame {

    FrmSplashScreen spl = this;
    
    /**
     * Creates new form SplashScreen
     */
    public FrmSplashScreen() {
        initComponents();
        startThread();
    }
    
    void startThread(){
    //FUNÇÃO PARA INICIAR O PROGRESSO COM SPLASH
        Thread hi = new Thread(new Runnable(){
           @Override
           //CHAMADA LOGIN
           public void run(){
                FrmLogin log = new FrmLogin(spl);
                log.setLocationRelativeTo(null);
                log.setVisible(true);
                dispose();
           }
        });
        hi.start();
    }        

    public JProgressBar getJProgressBar(){
        return Progresso;
    }    
    
    public JLabel getJLabel(){
        return lblCarregandoSistema;
    }             
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelProgresso = new javax.swing.JPanel();
        lblCarregandoSistema = new javax.swing.JLabel();
        Progresso = new javax.swing.JProgressBar();
        lblImagemSplash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setName("SplashScreen"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipal.setMinimumSize(new java.awt.Dimension(650, 645));
        jPanelPrincipal.setName("jPanelPrincipal"); // NOI18N
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(650, 645));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelProgresso.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProgresso.setName("jPanelProgresso"); // NOI18N
        jPanelProgresso.setPreferredSize(new java.awt.Dimension(650, 70));

        lblCarregandoSistema.setBackground(new java.awt.Color(255, 255, 255));
        lblCarregandoSistema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCarregandoSistema.setText("Carregando o sistema");
        lblCarregandoSistema.setName("lblCarregandoSistema"); // NOI18N

        Progresso.setName("Progresso"); // NOI18N

        javax.swing.GroupLayout jPanelProgressoLayout = new javax.swing.GroupLayout(jPanelProgresso);
        jPanelProgresso.setLayout(jPanelProgressoLayout);
        jPanelProgressoLayout.setHorizontalGroup(
            jPanelProgressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelProgressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarregandoSistema)
                    .addComponent(Progresso, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanelProgressoLayout.setVerticalGroup(
            jPanelProgressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarregandoSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Progresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jPanelProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 650, 70));

        lblImagemSplash.setBackground(new java.awt.Color(255, 255, 255));
        lblImagemSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal/logo.png"))); // NOI18N
        lblImagemSplash.setName("lblImagemSplash"); // NOI18N
        jPanelPrincipal.add(lblImagemSplash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmSplashScreen tela = new FrmSplashScreen();
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progresso;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelProgresso;
    private javax.swing.JLabel lblCarregandoSistema;
    private javax.swing.JLabel lblImagemSplash;
    // End of variables declaration//GEN-END:variables
}
