package formularios;

import Classes.Conectar;
import Classes.Criptografiar;
import Classes.Usuarios;
import ClassesDAO.UsuarioDAO;
import Formatadores.LetrasMaiusculas;
import GeradorID.gerarId;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static formularios.frmMenuPrincipal.JDesktopPanePrincipall;
import java.awt.Dimension;
/**
 *
 * @author João Carlos Batista
 */
public class FrmUsuario extends javax.swing.JInternalFrame {
    static Conectar cc = new Conectar();
    static Connection cn = cc.conexao();
    static PreparedStatement ps;
    String mensagem;
    int idAlteracao = 0;

    public FrmUsuario(int idAlteracao) {
        initComponents();
        txtNome.setDocument(new LetrasMaiusculas());
        txtLogin.setDocument(new LetrasMaiusculas());
        txtEmail.setDocument(new LetrasMaiusculas());
        this.idAlteracao = idAlteracao;        
        carregarUsuario(idAlteracao);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlCadastro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        jtxtSenha = new javax.swing.JPasswordField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Cadastro de usuário");
        setPreferredSize(new java.awt.Dimension(310, 368));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCadastro.setBackground(new java.awt.Color(255, 255, 255));
        pnlCadastro.setName("pnlCadastro"); // NOI18N
        pnlCadastro.setPreferredSize(new java.awt.Dimension(335, 290));
        pnlCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNome.setText("Nome");
        lblNome.setName("lblNome"); // NOI18N
        pnlCadastro.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNome.setName("txtNome"); // NOI18N
        txtNome.setPreferredSize(new java.awt.Dimension(260, 25));
        pnlCadastro.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 260, -1));

        lblLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblLogin.setText("Login");
        lblLogin.setName("lblLogin"); // NOI18N
        pnlCadastro.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, -1, -1));

        txtLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtLogin.setName("txtLogin"); // NOI18N
        txtLogin.setPreferredSize(new java.awt.Dimension(260, 25));
        pnlCadastro.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 260, -1));

        lblSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSenha.setText("Senha");
        lblSenha.setName("lblSenha"); // NOI18N
        pnlCadastro.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 150, -1, -1));

        jtxtSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtSenha.setMinimumSize(new java.awt.Dimension(6, 26));
        jtxtSenha.setName("jtxtSenha"); // NOI18N
        jtxtSenha.setPreferredSize(new java.awt.Dimension(260, 25));
        pnlCadastro.add(jtxtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 170, 260, -1));

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setName("lblLogin"); // NOI18N
        pnlCadastro.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 210, -1, -1));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtEmail.setName("txtEmail"); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(260, 25));
        pnlCadastro.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, 260, -1));

        btnSalvar.setBackground(new java.awt.Color(1, 50, 67));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlCadastro.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 280, -1, -1));

        btnFechar.setBackground(new java.awt.Color(249, 105, 14));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("Fechar");
        btnFechar.setBorderPainted(false);
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.setName("btnFechar"); // NOI18N
        btnFechar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        pnlCadastro.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        pnlPrincipal.add(pnlCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 335));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        FrmListaUsuario listaUsuario = new FrmListaUsuario();
        JDesktopPanePrincipall.add(listaUsuario);
        listaUsuario.setVisible(true);
        listaUsuario.setPosicao();
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (camposObrigatorios()) {
            JOptionPane.showMessageDialog(this, mensagem, "Alerta", 0,
                    new ImageIcon(getClass().getResource("/imagens/icons/info_P.png")));
        } else {
            Usuarios usuario = new Usuarios();            
            usuario.setUsu_Nom(txtNome.getText().trim());
            usuario.setUsu_Log(txtLogin.getText().trim());
            usuario.setUsu_Sen(new String(jtxtSenha.getPassword()).trim());
            usuario.setUsu_Ema(txtEmail.getText().trim());

            if (idAlteracao == 0){
                usuario.setUsu_Cod(gerarId.gerarIdUsuario());
                UsuarioDAO.gravarUsuario(usuario);
            } else {
                usuario.setUsu_Cod(idAlteracao);
                UsuarioDAO.alterar(usuario);                
            }

            FrmListaUsuario listaUsuario = new FrmListaUsuario();
            JDesktopPanePrincipall.add(listaUsuario);
            listaUsuario.setVisible(true);
            listaUsuario.setPosicao();
            dispose();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private boolean camposObrigatorios() {
        boolean retorno = false;
        mensagem = "Preenchimento obrigatório\n do(s) campo(s) abaixo:\n\n";

        if (txtNome.getText().equals("")) {
            mensagem += "Nome;\n";
            retorno = true;
        }

        if (txtLogin.getText().equals("")) {
            mensagem += "Login;\n";
            retorno = true;
        }

        if (jtxtSenha.getText().equals("")) {
            mensagem += "Senha;\n";
            retorno = true;
        }
        return retorno;
    }

    private void carregarUsuario(int cod) {
        String senha = "";
        if (cod > 0) {
            String sql = "SELECT usu_Nom, usu_Log, usu_Sen, usu_Ema FROM usuario WHERE usu_Cod =" + cod;
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    txtNome.setText(rs.getString("usu_Nom"));
                    txtLogin.setText(rs.getString("usu_Log"));
                    senha = rs.getString("usu_Sen");
                    jtxtSenha.setText(Criptografiar.decriptografar(senha));
                    txtEmail.setText(rs.getString("usu_Ema"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao tentar conectar ao banco de dados. ERRO: " + ex);
            }
        }
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPasswordField jtxtSenha;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
