package formularios;

import Classes.Veiculo;
import ClassesDao.VeiculoDAO;
import Formatadores.LetrasMaiusculas;
import Formatadores.TeclasNumericaAno;
import GeradorID.gerarId;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author João Carlos Batista
 */
public class FrmVeiculo extends javax.swing.JInternalFrame {

    private String documento;
    private String docAuxi;
    int idVeiculo = 0;
    int idCliente = 0;
    String placa = "000-0000";
    private String mensagem;

    public FrmVeiculo(int idVei, int idCli) {
        initComponents();
        jtxtPlaca.setDocument(new LetrasMaiusculas());
        txtModelo.setDocument(new LetrasMaiusculas());
        txtFabricante.setDocument(new LetrasMaiusculas());
        txtCor.setDocument(new LetrasMaiusculas());
        txtCombustivel.setDocument(new LetrasMaiusculas());
        txtChassi.setDocument(new LetrasMaiusculas());
        txtAnoFab.setDocument(new TeclasNumericaAno());
        this.idVeiculo = idVei;
        this.idCliente = idCli;

        if (idVeiculo > 0) {
            carregarVeiculo(idVeiculo);
        }                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        jtxtPlaca = new javax.swing.JFormattedTextField();
        lblFabricante = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblAnoFab = new javax.swing.JLabel();
        txtAnoFab = new javax.swing.JTextField();
        lblCombustivel = new javax.swing.JLabel();
        txtCombustivel = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblChassi = new javax.swing.JLabel();
        txtChassi = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Cadastro de veículo");
        setPreferredSize(new java.awt.Dimension(620, 250));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(540, 350));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPlaca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPlaca.setText("Placa");
        lblPlaca.setName("lblPlaca"); // NOI18N
        pnlPrincipal.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, -1, -1));

        jtxtPlaca.setForeground(new java.awt.Color(51, 51, 51));
        try {
            jtxtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxtPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtxtPlaca.setPreferredSize(new java.awt.Dimension(90, 25));
        jtxtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtPlacaFocusLost(evt);
            }
        });
        pnlPrincipal.add(jtxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 90, -1));

        lblFabricante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFabricante.setText("Fabricante");
        lblFabricante.setName("lblFabricante"); // NOI18N
        pnlPrincipal.add(lblFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 30, -1, -1));

        txtFabricante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFabricante.setForeground(new java.awt.Color(51, 51, 51));
        txtFabricante.setName("txtFabricante"); // NOI18N
        txtFabricante.setPreferredSize(new java.awt.Dimension(140, 25));
        txtFabricante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFabricanteFocusLost(evt);
            }
        });
        txtFabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFabricanteKeyPressed(evt);
            }
        });
        pnlPrincipal.add(txtFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 50, 140, -1));

        lblModelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblModelo.setText("Modelo");
        lblModelo.setName("lblModelo"); // NOI18N
        pnlPrincipal.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 30, -1, -1));

        txtModelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(51, 51, 51));
        txtModelo.setName("txtModelo"); // NOI18N
        txtModelo.setPreferredSize(new java.awt.Dimension(190, 25));
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 50, 190, -1));

        lblAnoFab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAnoFab.setText("Ano Fab.");
        lblAnoFab.setName("lblAnoFab"); // NOI18N
        pnlPrincipal.add(lblAnoFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 30, -1, -1));

        txtAnoFab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAnoFab.setForeground(new java.awt.Color(51, 51, 51));
        txtAnoFab.setName("txtAnoFab"); // NOI18N
        txtAnoFab.setPreferredSize(new java.awt.Dimension(90, 25));
        txtAnoFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoFabActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtAnoFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 50, 90, -1));

        lblCombustivel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCombustivel.setText("Combustível");
        lblCombustivel.setName("lblCombustivel"); // NOI18N
        pnlPrincipal.add(lblCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, -1, -1));

        txtCombustivel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCombustivel.setForeground(new java.awt.Color(51, 51, 51));
        txtCombustivel.setName("txtCombustivel"); // NOI18N
        txtCombustivel.setPreferredSize(new java.awt.Dimension(120, 25));
        txtCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCombustivelActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 120, -1));

        lblCor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCor.setText("Cor");
        lblCor.setName("lblCor"); // NOI18N
        pnlPrincipal.add(lblCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 90, -1, -1));

        txtCor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCor.setForeground(new java.awt.Color(51, 51, 51));
        txtCor.setName("txtCor"); // NOI18N
        txtCor.setPreferredSize(new java.awt.Dimension(120, 25));
        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 110, 120, -1));

        lblChassi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblChassi.setText("Chassi");
        lblChassi.setName("lblChassi"); // NOI18N
        pnlPrincipal.add(lblChassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 90, -1, -1));

        txtChassi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtChassi.setForeground(new java.awt.Color(51, 51, 51));
        txtChassi.setName("txtChassi"); // NOI18N
        txtChassi.setPreferredSize(new java.awt.Dimension(160, 25));
        txtChassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChassiActionPerformed(evt);
            }
        });
        pnlPrincipal.add(txtChassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 110, 160, -1));

        btnFechar.setBackground(new java.awt.Color(249, 105, 14));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFechar.setForeground(new java.awt.Color(255, 255, 255));
        btnFechar.setText("Fechar");
        btnFechar.setBorderPainted(false);
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.setName("btnFechar"); // NOI18N
        btnFechar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFecharMouseExited(evt);
            }
        });
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        btnSalvar.setBackground(new java.awt.Color(1, 50, 67));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.setPreferredSize(new java.awt.Dimension(90, 40));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 160, -1, -1));

        getContentPane().add(pnlPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtAnoFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoFabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoFabActionPerformed

    private void btnFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseEntered
        btnFechar.setBackground(new Color(249, 105, 40));
        btnFechar.setForeground(Color.WHITE);
        btnFechar.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnFecharMouseEntered

    private void btnFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseExited
        btnFechar.setBackground(new Color(249, 105, 14));
        btnFechar.setForeground(Color.WHITE);
        btnFechar.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnFecharMouseExited

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        FrmProprietarioVeiculo cliente = new FrmProprietarioVeiculo(idCliente, "V");
        frmMenuPrincipal.JDesktopPanePrincipall.add(cliente);
        cliente.setVisible(true);
        cliente.setPosicao();
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        btnSalvar.setBackground(new Color(1, 50, 90));////(58, 83, 155));
        btnSalvar.setForeground(Color.WHITE);
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 16));
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        btnSalvar.setBackground(new Color(1, 50, 67));
        btnSalvar.setForeground(Color.WHITE);
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 14));
    }//GEN-LAST:event_btnSalvarMouseExited

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        if (verificarExitenciaVeiculo()) {
            if (camposObrigatorios()) {
                JOptionPane.showMessageDialog(this, mensagem, "Alerta", 0,
                        new ImageIcon(getClass().getResource("/imagens/icons/info_P.png")));
            } else {
                Veiculo veiculo = new Veiculo();
                veiculo.setVei_Cod(idVeiculo);
                veiculo.setVei_Cli_Cod(idCliente);
                veiculo.setVei_Placa(jtxtPlaca.getText().trim());
                veiculo.setVei_Fab(txtFabricante.getText().trim());
                veiculo.setVei_Mod(txtModelo.getText().trim());
                if (txtAnoFab.getText().trim().isEmpty()) {
                    veiculo.setVei_Ano_Fab(0);
                } else {
                    veiculo.setVei_Ano_Fab(Integer.parseInt(txtAnoFab.getText()));
                }
                veiculo.setVei_Com(txtCombustivel.getText().trim());
                veiculo.setVei_Cor(txtCor.getText().trim());
                veiculo.setVei_Chassi(txtChassi.getText().trim());

                if (idVeiculo > 0) {
                    VeiculoDAO.alterarVeiculo(veiculo);
                    placa = veiculo.getVei_Placa();
                } else {                    
                    veiculo.setVei_Cod(gerarId.gerarIDVeiculo());
                    idVeiculo = veiculo.getVei_Cod();
                    placa = veiculo.getVei_Placa();
                    VeiculoDAO.gravarVeiculo(veiculo);
                }                
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtFabricanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFabricanteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFabricanteKeyPressed

    private void txtFabricanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFabricanteFocusLost

    }//GEN-LAST:event_txtFabricanteFocusLost

    private void txtCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCombustivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCombustivelActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtChassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChassiActionPerformed

    private void jtxtPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPlacaFocusLost

    }//GEN-LAST:event_jtxtPlacaFocusLost

    private void carregarVeiculo(int cod) {
        Veiculo veiculo = VeiculoDAO.carregarVeiculo(cod);
        jtxtPlaca.setText(veiculo.getVei_Placa());
        placa = veiculo.getVei_Placa();
        txtFabricante.setText(veiculo.getVei_Fab());
        txtModelo.setText(veiculo.getVei_Mod());
        if (veiculo.getVei_Ano_Fab() > 0) {
            txtAnoFab.setText(Integer.toString(veiculo.getVei_Ano_Fab()));
        } else {
            txtAnoFab.setText("");
        }
        txtCombustivel.setText(veiculo.getVei_Com());
        txtCor.setText(veiculo.getVei_Cor());
        txtChassi.setText(veiculo.getVei_Chassi());
    }

    private boolean camposObrigatorios() {
        boolean retorno = false;
        mensagem = "Preenchimento obrigatório\n do(s) campo(s) abaixo:\n\n";
        if (txtFabricante.getText().trim().equals("")) {
            mensagem += "Fabricante;\n";
            retorno = true;
        }

        if (txtModelo.getText().trim().equals("")) {
            mensagem += "Modelo;\n";
            retorno = true;
        }

        if (jtxtPlaca.getText().trim().length() <= 1) {
            mensagem += "Placa;";
            retorno = true;
        }
        return retorno;
    }
    
    private boolean verificarExitenciaVeiculo() {
        Veiculo veiculo;
        //String placa = jtxtPlaca.getText().trim();
        if (idVeiculo == 0 || !placa.equals(jtxtPlaca.getText().trim())) {
            if (jtxtPlaca.getText().trim().length() > 1) {
                veiculo = VeiculoDAO.consultarExistenciaVeiculo(jtxtPlaca.getText().trim());

                if (veiculo.getVei_Cli_Cod() > 0) {
                    if (idCliente == veiculo.getVei_Cli_Cod()) {
                        JOptionPane.showMessageDialog(this, "A placa " + jtxtPlaca.getText().trim() + " já está cadastrada para este cliente.", "Alerta", 0,
                                new ImageIcon(getClass().getResource("/imagens/icons/info_P.png")));
                        return false;
                    } else {
                        if (idCliente != veiculo.getVei_Cli_Cod()) {
                            JOptionPane.showMessageDialog(this, "A placa " + jtxtPlaca.getText().trim() + " já está cadastrada para o cliente " + veiculo.getCli_Nom() + ".", "Alerta", 0,
                                    new ImageIcon(getClass().getResource("/imagens/icons/info_P.png")));
                            return false;
                        }
                    }
                }
            }
        }//////
        return true;
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JFormattedTextField jtxtPlaca;
    private javax.swing.JLabel lblAnoFab;
    private javax.swing.JLabel lblChassi;
    private javax.swing.JLabel lblCombustivel;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtAnoFab;
    private javax.swing.JTextField txtChassi;
    private javax.swing.JTextField txtCombustivel;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
