/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formatadores;

import ClassesEnum.Pessoas;
import ConexaoBancoDados.ConexaoBancoDados;
import com.toedter.calendar.JTextFieldDateEditor;
import javafx.collections.FXCollections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author João Carlos Batista
 */
public class CapturarTecla extends javax.swing.JFrame {

    /**
     * Creates new form CapturarTecla
     */
    public CapturarTecla() {
        initComponents();
        //txtTel.setDocument(new LetrasMaiusculas());
       // cmbPessoa.setModel(new DefaultComboBoxModel(Pessoas.values()));
        //cmbPessoa.setSelectedIndex(0);
       // moeda = new JTextField(8);
       // moeda.setDocument(new MonetarioDocument());
        //moeda.setText("157000");
        txtMascara.setDocument(new teclaNumerica());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTeclaPressionada = new javax.swing.JLabel();
        txtTeclaPressionada = new javax.swing.JTextField();
        lblCodigoTeclaPressionada = new javax.swing.JLabel();
        txtCodigoTeclaPressionada = new javax.swing.JTextField();
        btnConectarMYSQL = new javax.swing.JButton();
        btnExecuteSQL = new javax.swing.JButton();
        lblTeclaPressionada1 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        btnMascara = new javax.swing.JButton();
        cmbPessoa = new javax.swing.JComboBox<>();
        txtMascara = new javax.swing.JTextField();
        moeda = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTeclaPressionada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTeclaPressionada.setText("Tecla pressionada:");
        lblTeclaPressionada.setName("lblTeclaPressionada"); // NOI18N

        txtTeclaPressionada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTeclaPressionada.setName("txtTeclaPressionada"); // NOI18N
        txtTeclaPressionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeclaPressionadaActionPerformed(evt);
            }
        });
        txtTeclaPressionada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTeclaPressionadaKeyPressed(evt);
            }
        });

        lblCodigoTeclaPressionada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCodigoTeclaPressionada.setText("Código da Tecla:");
        lblCodigoTeclaPressionada.setName("lblCodigoTeclaPressionada"); // NOI18N

        txtCodigoTeclaPressionada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigoTeclaPressionada.setName("txtCodigoTeclaPressionada"); // NOI18N
        txtCodigoTeclaPressionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoTeclaPressionadaActionPerformed(evt);
            }
        });

        btnConectarMYSQL.setText("Conectar no Banco MYSQL");
        btnConectarMYSQL.setName("btnConectarMYSQL"); // NOI18N
        btnConectarMYSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarMYSQLActionPerformed(evt);
            }
        });

        btnExecuteSQL.setText("ExecuteSQL");
        btnExecuteSQL.setName("btnExecuteSQL"); // NOI18N
        btnExecuteSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteSQLActionPerformed(evt);
            }
        });

        lblTeclaPressionada1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTeclaPressionada1.setText("Tel");
        lblTeclaPressionada1.setName("lblTel"); // NOI18N

        txtTel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTel.setName("txtTel"); // NOI18N
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelKeyPressed(evt);
            }
        });

        btnMascara.setText("Mascara");
        btnMascara.setName("btnMascara"); // NOI18N
        btnMascara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMascaraActionPerformed(evt);
            }
        });

        cmbPessoa.setEditable(true);
        cmbPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joao Carlos", "Cassio", "Adriano", "Alexandre", "Maria Da Penha", "José" }));
        cmbPessoa.setName("cmbPessoa"); // NOI18N

        txtMascara.setName("txtMascara"); // NOI18N

        moeda.setName("moeda"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConectarMYSQL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExecuteSQL)
                        .addGap(27, 27, 27)
                        .addComponent(btnMascara, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTeclaPressionada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTeclaPressionada, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCodigoTeclaPressionada)
                                    .addComponent(lblTeclaPressionada1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigoTeclaPressionada, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moeda, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtMascara, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeclaPressionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeclaPressionada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoTeclaPressionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoTeclaPressionada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTeclaPressionada1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMascara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moeda, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConectarMYSQL)
                    .addComponent(btnExecuteSQL)
                    .addComponent(btnMascara))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeclaPressionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeclaPressionadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeclaPressionadaActionPerformed

    private void txtCodigoTeclaPressionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoTeclaPressionadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoTeclaPressionadaActionPerformed

    private void txtTeclaPressionadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeclaPressionadaKeyPressed
        txtCodigoTeclaPressionada.setText(""+evt.getKeyCode());
    }//GEN-LAST:event_txtTeclaPressionadaKeyPressed

    private void btnConectarMYSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarMYSQLActionPerformed
        
        ConexaoBancoDados conexaoBancoDados = new ConexaoBancoDados();
        conexaoBancoDados.conecta();
        conexaoBancoDados.desconectar();
        
    }//GEN-LAST:event_btnConectarMYSQLActionPerformed

    private void btnExecuteSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteSQLActionPerformed
        ConexaoBancoDados conexaoBancoDados = new ConexaoBancoDados();
        conexaoBancoDados.conecta();
        conexaoBancoDados.executaSQL("SELECT * FROM cliente;");
        conexaoBancoDados.desconectar();        
    }//GEN-LAST:event_btnExecuteSQLActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelKeyPressed

    private void btnMascaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMascaraActionPerformed
        //txtTel.setText(FormatadorMascara.formatMascTelCel(txtTel.getText()));
        
        /*
        String temp = moeda.getText();
        temp = temp.replace(".", "");
        temp = temp.replace(",", ".");
        double real = new Double(temp);
        JOptionPane.showMessageDialog(null, "Não foi possível inserir o novo cliente: " + real);
        */
        
        
    }//GEN-LAST:event_btnMascaraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapturarTecla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapturarTecla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapturarTecla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapturarTecla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CapturarTecla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarMYSQL;
    private javax.swing.JButton btnExecuteSQL;
    private javax.swing.JButton btnMascara;
    private javax.swing.JComboBox<String> cmbPessoa;
    private javax.swing.JLabel lblCodigoTeclaPressionada;
    private javax.swing.JLabel lblTeclaPressionada;
    private javax.swing.JLabel lblTeclaPressionada1;
    private javax.swing.JFormattedTextField moeda;
    private javax.swing.JTextField txtCodigoTeclaPressionada;
    private javax.swing.JTextField txtMascara;
    private javax.swing.JTextField txtTeclaPressionada;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
